-- 1. Tabel Peserta
CREATE TABLE IF NOT EXISTS public.peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    nama_peserta TEXT,
    kelompok TEXT DEFAULT '-',
    nfc_uid TEXT,
    serial_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabel NFC Peserta
CREATE TABLE IF NOT EXISTS public.nfc_peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nfc_uid TEXT NOT NULL,
    peserta_id BIGINT REFERENCES public.peserta(id) ON DELETE SET NULL,
    nama TEXT,
    nama_peserta TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabel Sesi Absensi
CREATE TABLE IF NOT EXISTS public.sesi_absensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_sesi TEXT NOT NULL,
    tanggal DATE,
    jam_mulai TIME,
    jam_selesai TIME,
    is_active BOOLEAN DEFAULT true,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabel Riwayat Absen (Tabel Utama Penyimpanan Presensi)
CREATE TABLE IF NOT EXISTS public.riwayat_absen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT,
    nama_peserta TEXT,
    peserta_id BIGINT REFERENCES public.peserta(id) ON DELETE SET NULL,
    sesi_nama TEXT,
    status TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabel Kehadiran (Tabel Fallback / Opsional sesuai dengan code lama)
CREATE TABLE IF NOT EXISTS public.kehadiran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT,
    nama TEXT,
    sesi_nama TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
