-- =========================================================================
-- SKEMA LENGKAP SUPABASE (POSTGRESQL) - SISTEM PRESENSI & PLOTTING CAI
-- =========================================================================
-- Petunjuk:
-- Salin seluruh kode SQL ini dan jalankan (Run) di Supabase Dashboard:
-- Masuk ke project Supabase Anda -> menu "SQL Editor" -> "New Query" -> Tempel & "Run".
-- =========================================================================

-- 1. TABEL UTAMA: PESERTA (Lengkap dengan seluruh kolom data & plotting)
CREATE TABLE IF NOT EXISTS public.peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    nama_peserta TEXT,
    jenis_kelamin VARCHAR(10) DEFAULT 'L',        -- 'L' (Laki-laki) / 'P' (Perempuan)
    kelompok TEXT DEFAULT '-',                     -- Kelompok / Desa / Daerah
    dapukan TEXT DEFAULT 'Peserta',                -- Dapukan (Peserta, Panitia, Pengurus, dsb)
    tenda TEXT DEFAULT '-',                        -- Plotting Tenda (misal: Tenda 01, Tenda 02, atau '-')
    grup_fgd TEXT DEFAULT '-',                     -- Plotting Kelas / Grup FGD (misal: Pegon SMP, Bacaan SMP, atau '-')
    smartcard TEXT,                                -- Nomor / UID Smartcard NFC
    nfc_uid TEXT,                                  -- UID kartu NFC fisik
    uid_nfc TEXT,                                  -- Alias UID NFC
    serial_number TEXT,                            -- Nomor Seri Kartu
    no_hp TEXT,                                    -- Nomor WhatsApp / Telepon
    foto_url TEXT,                                 -- URL Foto Profil Santri
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. TABEL NFC PESERTA (Registrasi Smartcard & Pemetaan UID)
CREATE TABLE IF NOT EXISTS public.nfc_peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nfc_uid TEXT NOT NULL UNIQUE,
    peserta_id BIGINT REFERENCES public.peserta(id) ON DELETE SET NULL,
    nama TEXT,
    nama_peserta TEXT,
    jenis_kelamin VARCHAR(10) DEFAULT 'L',
    kelompok TEXT DEFAULT '-',
    dapukan TEXT DEFAULT 'Peserta',
    tenda TEXT DEFAULT '-',
    grup_fgd TEXT DEFAULT '-',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABEL SESI ABSENSI & JADWAL KEGIATAN
CREATE TABLE IF NOT EXISTS public.sesi_absensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_sesi TEXT NOT NULL,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    jam_mulai TIME NOT NULL,
    jam_selesai TIME NOT NULL,
    is_active BOOLEAN DEFAULT true,
    keterangan TEXT,
    jadwal TEXT DEFAULT 'materi',                  -- Kategori: 'materi', 'sholat', 'kegiatan', 'makan'
    kategori TEXT DEFAULT 'materi',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Alias tabel jadwal_absensi untuk sinkronisasi
CREATE TABLE IF NOT EXISTS public.jadwal_absensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_sesi TEXT NOT NULL,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    jam_mulai TIME NOT NULL,
    jam_selesai TIME NOT NULL,
    is_active BOOLEAN DEFAULT true,
    keterangan TEXT,
    jadwal TEXT DEFAULT 'materi',
    kategori TEXT DEFAULT 'materi',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABEL RIWAYAT ABSENSI (Log Tap NFC & Presensi Real-time)
CREATE TABLE IF NOT EXISTS public.riwayat_absen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peserta_id BIGINT REFERENCES public.peserta(id) ON DELETE SET NULL,
    nama_peserta TEXT,
    serial_number TEXT,
    sesi_nama TEXT NOT NULL,
    jadwal TEXT DEFAULT 'materi',
    kategori TEXT DEFAULT 'materi',
    status TEXT DEFAULT 'Hadir',                   -- 'Hadir', 'Izin', 'Sakit', 'Terlambat'
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabel Kehadiran (Tabel log tambahan / fallback)
CREATE TABLE IF NOT EXISTS public.kehadiran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT,
    nama TEXT,
    sesi_nama TEXT,
    jadwal TEXT DEFAULT 'materi',
    kategori TEXT DEFAULT 'materi',
    status TEXT DEFAULT 'Hadir',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABEL PLOTTING TENDA & PLOTTING FGD (Master Data Tenda & Kelas Diskusi)
CREATE TABLE IF NOT EXISTS public.plotting_tenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL UNIQUE,
    ketua TEXT DEFAULT '-',
    ketua_l TEXT DEFAULT '-',
    ketua_p TEXT DEFAULT '-',
    kapasitas INTEGER DEFAULT 50,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.plotting_fgd (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL UNIQUE,
    ketua TEXT DEFAULT '-',
    ketua_l TEXT DEFAULT '-',
    ketua_p TEXT DEFAULT '-',
    kapasitas INTEGER DEFAULT 50,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Alias tabel untuk kompatibilitas jika query langsung ke tenda / grup_fgd
CREATE TABLE IF NOT EXISTS public.tenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL UNIQUE,
    ketua TEXT DEFAULT '-',
    ketua_l TEXT DEFAULT '-',
    ketua_p TEXT DEFAULT '-',
    kapasitas INTEGER DEFAULT 50,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.grup_fgd (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL UNIQUE,
    ketua TEXT DEFAULT '-',
    ketua_l TEXT DEFAULT '-',
    ketua_p TEXT DEFAULT '-',
    kapasitas INTEGER DEFAULT 50,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. TABEL RIWAYAT MUTASI PLOTTING (Log Pemindahan Kelas / Tenda)
CREATE TABLE IF NOT EXISTS public.riwayat_mutasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peserta_id BIGINT REFERENCES public.peserta(id) ON DELETE CASCADE,
    nama_peserta TEXT,
    tipe_plotting TEXT NOT NULL,                   -- 'tenda' atau 'fgd'
    tujuan_sebelum TEXT DEFAULT '-',
    tujuan_baru TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Inisialisasi Data Master Awal Tenda & FGD (Jika Kosong)
INSERT INTO public.plotting_tenda (nama, ketua)
VALUES 
    ('Tenda 01', '-'),
    ('Tenda 02', '-'),
    ('Tenda 03', '-'),
    ('Tenda 04', '-')
ON CONFLICT (nama) DO NOTHING;

INSERT INTO public.plotting_fgd (nama, ketua)
VALUES 
    ('Pegon SMP', '-'),
    ('Bacaan SMP', '-'),
    ('Lambatan SMP', '-'),
    ('Cepatan SMP', '-')
ON CONFLICT (nama) DO NOTHING;

-- =========================================================================
-- MIGRATION: Menambahkan kolom-kolom baru jika tabel sudah pernah dibuat sebelumnya
-- =========================================================================
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS nama_peserta TEXT;
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS jenis_kelamin VARCHAR(10) DEFAULT 'L';
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS kelompok TEXT DEFAULT '-';
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS dapukan TEXT DEFAULT 'Peserta';
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS tenda TEXT DEFAULT '-';
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS grup_fgd TEXT DEFAULT '-';
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS smartcard TEXT;
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS nfc_uid TEXT;
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS uid_nfc TEXT;
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS serial_number TEXT;
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS no_hp TEXT;
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS foto_url TEXT;
ALTER TABLE public.peserta ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

ALTER TABLE public.plotting_tenda ADD COLUMN IF NOT EXISTS ketua TEXT DEFAULT '-';
ALTER TABLE public.plotting_tenda ADD COLUMN IF NOT EXISTS ketua_l TEXT DEFAULT '-';
ALTER TABLE public.plotting_tenda ADD COLUMN IF NOT EXISTS ketua_p TEXT DEFAULT '-';
ALTER TABLE public.plotting_tenda ADD COLUMN IF NOT EXISTS kapasitas INTEGER DEFAULT 50;

ALTER TABLE public.plotting_fgd ADD COLUMN IF NOT EXISTS ketua TEXT DEFAULT '-';
ALTER TABLE public.plotting_fgd ADD COLUMN IF NOT EXISTS ketua_l TEXT DEFAULT '-';
ALTER TABLE public.plotting_fgd ADD COLUMN IF NOT EXISTS ketua_p TEXT DEFAULT '-';
ALTER TABLE public.plotting_fgd ADD COLUMN IF NOT EXISTS kapasitas INTEGER DEFAULT 50;

ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS jenis_kelamin VARCHAR(10) DEFAULT 'L';
ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS kelompok TEXT DEFAULT '-';
ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS dapukan TEXT DEFAULT 'Peserta';
ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS tenda TEXT DEFAULT '-';
ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS grup_fgd TEXT DEFAULT '-';

ALTER TABLE public.sesi_absensi ADD COLUMN IF NOT EXISTS jadwal TEXT DEFAULT 'materi';
ALTER TABLE public.sesi_absensi ADD COLUMN IF NOT EXISTS kategori TEXT DEFAULT 'materi';

ALTER TABLE public.jadwal_absensi ADD COLUMN IF NOT EXISTS jadwal TEXT DEFAULT 'materi';
ALTER TABLE public.jadwal_absensi ADD COLUMN IF NOT EXISTS kategori TEXT DEFAULT 'materi';

ALTER TABLE public.riwayat_absen ADD COLUMN IF NOT EXISTS jadwal TEXT DEFAULT 'materi';
ALTER TABLE public.riwayat_absen ADD COLUMN IF NOT EXISTS kategori TEXT DEFAULT 'materi';
ALTER TABLE public.riwayat_absen ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Hadir';

-- =========================================================================
-- INDEXING: Untuk performa pencarian, plotting, dan scanning NFC super cepat
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_peserta_nama ON public.peserta(nama);
CREATE INDEX IF NOT EXISTS idx_peserta_kelompok ON public.peserta(kelompok);
CREATE INDEX IF NOT EXISTS idx_peserta_tenda ON public.peserta(tenda);
CREATE INDEX IF NOT EXISTS idx_peserta_grup_fgd ON public.peserta(grup_fgd);
CREATE INDEX IF NOT EXISTS idx_peserta_smartcard ON public.peserta(smartcard);
CREATE INDEX IF NOT EXISTS idx_peserta_nfc_uid ON public.peserta(nfc_uid);
CREATE INDEX IF NOT EXISTS idx_nfc_peserta_uid ON public.nfc_peserta(nfc_uid);
CREATE INDEX IF NOT EXISTS idx_plotting_tenda_nama ON public.plotting_tenda(nama);
CREATE INDEX IF NOT EXISTS idx_plotting_fgd_nama ON public.plotting_fgd(nama);
CREATE INDEX IF NOT EXISTS idx_riwayat_absen_peserta ON public.riwayat_absen(peserta_id);
CREATE INDEX IF NOT EXISTS idx_riwayat_absen_sesi ON public.riwayat_absen(sesi_nama);

-- =========================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Memberikan hak akses penuh (SELECT, INSERT, UPDATE, DELETE) untuk web app
-- =========================================================================
ALTER TABLE public.peserta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfc_peserta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sesi_absensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jadwal_absensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.riwayat_absen ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kehadiran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.riwayat_mutasi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plotting_tenda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plotting_fgd ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grup_fgd ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access peserta" ON public.peserta;
CREATE POLICY "Allow full access peserta" ON public.peserta FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access nfc_peserta" ON public.nfc_peserta;
CREATE POLICY "Allow full access nfc_peserta" ON public.nfc_peserta FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access sesi_absensi" ON public.sesi_absensi;
CREATE POLICY "Allow full access sesi_absensi" ON public.sesi_absensi FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access jadwal_absensi" ON public.jadwal_absensi;
CREATE POLICY "Allow full access jadwal_absensi" ON public.jadwal_absensi FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access riwayat_absen" ON public.riwayat_absen;
CREATE POLICY "Allow full access riwayat_absen" ON public.riwayat_absen FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access kehadiran" ON public.kehadiran;
CREATE POLICY "Allow full access kehadiran" ON public.kehadiran FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access riwayat_mutasi" ON public.riwayat_mutasi;
CREATE POLICY "Allow full access riwayat_mutasi" ON public.riwayat_mutasi FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access plotting_tenda" ON public.plotting_tenda;
CREATE POLICY "Allow full access plotting_tenda" ON public.plotting_tenda FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access plotting_fgd" ON public.plotting_fgd;
CREATE POLICY "Allow full access plotting_fgd" ON public.plotting_fgd FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access tenda" ON public.tenda;
CREATE POLICY "Allow full access tenda" ON public.tenda FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access grup_fgd" ON public.grup_fgd;
CREATE POLICY "Allow full access grup_fgd" ON public.grup_fgd FOR ALL USING (true) WITH CHECK (true);
