"use client";

import { useState, useEffect, useCallback } from "react";
import { Nfc, Search, Check, Save, AlertCircle, CheckCircle2, Copy, RefreshCw, UserCheck, Database, Code, Info } from "lucide-react";
import { supabase } from "@/lib/supabase";

interface Peserta {
  id: number;
  nama: string;
  kelompok: string;
}

const NFC_TABLE_SQL = `-- Skrip SQL untuk membuat tabel 'nfc_peserta' di Supabase
-- Jalankan di Supabase Dashboard > SQL Editor > Run

CREATE TABLE IF NOT EXISTS public.nfc_peserta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nfc_uid TEXT UNIQUE NOT NULL,
  peserta_id BIGINT REFERENCES public.peserta(id) ON DELETE CASCADE,
  nama TEXT NOT NULL,
  kelompok TEXT DEFAULT '-'
);

-- Aktifkan RLS dan Kebijakan Akses Penuh
ALTER TABLE public.nfc_peserta ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access nfc_peserta" ON public.nfc_peserta;
CREATE POLICY "Allow full access nfc_peserta"
ON public.nfc_peserta
FOR ALL
USING (true)
WITH CHECK (true);`;

export default function InputNFCPesertaForm() {
  const [scannedUID, setScannedUID] = useState<string>("");
  const [isScanning, setIsScanning] = useState(false);
  const [isSupported, setIsSupported] = useState<boolean | null>(null);

  const [pesertaList, setPesertaList] = useState<Peserta[]>([]);
  const [loadingPeserta, setLoadingPeserta] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedPeserta, setSelectedPeserta] = useState<Peserta | null>(null);

  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error" | "info"; text: string } | null>(null);
  const [copiedSql, setCopiedSql] = useState(false);
  const [showSql, setShowSql] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setIsSupported("NDEFReader" in window);
    }
    fetchPeserta();
  }, []);

  const fetchPeserta = async () => {
    setLoadingPeserta(true);
    try {
      const { data, error } = await supabase
        .from("peserta")
        .select("id, nama, kelompok")
        .order("nama", { ascending: true });

      if (error) {
        console.error("Error fetching peserta:", error);
      } else {
        setPesertaList(data || []);
      }
    } catch (err) {
      console.error("Error fetching peserta:", err);
    } finally {
      setLoadingPeserta(false);
    }
  };

  const handleScanNFC = useCallback(async () => {
    if (!("NDEFReader" in window)) {
      setMessage({
        type: "error",
        text: "Browser/Perangkat tidak mendukung Web NFC. Anda juga dapat mengetik UID kartu secara manual.",
      });
      return;
    }

    try {
      setIsScanning(true);
      setMessage({
        type: "info",
        text: "Silakan tempelkan kartu NFC ke area sensor perangkat...",
      });

      // @ts-ignore
      const ndef = new NDEFReader();
      await ndef.scan();

      ndef.addEventListener("reading", ({ serialNumber }: any) => {
        if (serialNumber) {
          const formattedUID = serialNumber.toUpperCase();
          setScannedUID(formattedUID);
          setIsScanning(false);
          setMessage({
            type: "success",
            text: `Kartu NFC terdeteksi! UID: ${formattedUID}`,
          });

          if (navigator.vibrate) {
            navigator.vibrate(200);
          }
        }
      });

      ndef.addEventListener("readingerror", () => {
        setIsScanning(false);
        setMessage({
          type: "error",
          text: "Gagal membaca kartu NFC. Silakan coba lagi.",
        });
      });
    } catch (error: any) {
      setIsScanning(false);
      setMessage({
        type: "error",
        text: `Gagal mengaktifkan sensor NFC: ${error.message || error}`,
      });
    }
  }, []);

  const stopScan = () => {
    setIsScanning(false);
    setMessage(null);
  };

  const handleSaveNFC = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!scannedUID.trim()) {
      setMessage({ type: "error", text: "UID Kartu NFC belum ada. Tap kartu terlebih dahulu atau ketik UID manual." });
      return;
    }
    if (!selectedPeserta) {
      setMessage({ type: "error", text: "Silakan pilih nama peserta terlebih dahulu." });
      return;
    }

    setSaving(true);
    setMessage(null);

    const uidClean = scannedUID.trim().toUpperCase();

    try {
      // Upsert or Insert to nfc_peserta table
      const { data, error } = await supabase
        .from("nfc_peserta")
        .upsert(
          [
            {
              nfc_uid: uidClean,
              peserta_id: selectedPeserta.id,
              nama: selectedPeserta.nama,
              kelompok: selectedPeserta.kelompok,
            },
          ],
          { onConflict: "nfc_uid" }
        )
        .select();

      if (error) {
        // Check for fallback insert if upsert fails
        const { error: insertErr } = await supabase.from("nfc_peserta").insert([
          {
            nfc_uid: uidClean,
            peserta_id: selectedPeserta.id,
            nama: selectedPeserta.nama,
            kelompok: selectedPeserta.kelompok,
          },
        ]);

        if (insertErr) {
          throw insertErr;
        }
      }

      setMessage({
        type: "success",
        text: `Berhasil menyimpan data NFC! Kartu [${uidClean}] terhubung dengan "${selectedPeserta.nama}" (${selectedPeserta.kelompok}).`,
      });

      // Reset selection
      setScannedUID("");
      setSelectedPeserta(null);
      setSearchTerm("");
    } catch (err: any) {
      console.error("Error saving NFC peserta:", err);
      let detail = err.message || "Gagal menyimpan data NFC peserta.";
      if (err.code === "42P01" || detail.toLowerCase().includes("does not exist")) {
        detail = "Tabel 'nfc_peserta' belum dibuat di Supabase. Silakan jalankan Kode SQL di bawah untuk membuat tabelnya.";
        setShowSql(true);
      } else if (err.code === "42501" || detail.toLowerCase().includes("row-level security")) {
        detail = "Akses ditolak oleh RLS Supabase pada tabel 'nfc_peserta'. Jalankan skrip SQL di bawah untuk mengaktifkan kebijakan RLS.";
        setShowSql(true);
      }
      setMessage({ type: "error", text: detail });
    } finally {
      setSaving(false);
    }
  };

  const copySqlCode = () => {
    navigator.clipboard.writeText(NFC_TABLE_SQL);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  const filteredPeserta = pesertaList.filter(
    (p) =>
      p.nama.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (p.kelompok && p.kelompok.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Page Title Header */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Nfc className="w-6 h-6 text-[#203598]" />
            Input Data NFC Peserta
          </h2>
          <p className="text-slate-500 text-xs mt-1">
            Hubungkan kartu fisik NFC dengan nama peserta terdaftar.
          </p>
        </div>
        <button
          onClick={() => setShowSql(!showSql)}
          className="px-3 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-2 transition-colors border border-slate-200"
        >
          <Code className="w-4 h-4 text-[#203598]" />
          {showSql ? "Sembunyikan Kode SQL" : "Kode SQL Tabel NFC"}
        </button>
      </div>

      {/* SQL Script Card (Toggleable) */}
      {showSql && (
        <div className="bg-slate-900 text-slate-100 rounded-2xl p-6 shadow-xl border border-slate-800 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm">
              <Database className="w-5 h-5" />
              <span>Kode SQL Tabel &apos;nfc_peserta&apos;</span>
            </div>
            <button
              onClick={copySqlCode}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors border border-slate-700"
            >
              {copiedSql ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  Tersalin!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Salin SQL
                </>
              )}
            </button>
          </div>
          <p className="text-xs text-slate-400">
            Jalankan skrip ini di <strong>Supabase Dashboard &gt; SQL Editor &gt; Run</strong> untuk membuat tabel nfc_peserta.
          </p>
          <pre className="bg-black/50 p-4 rounded-xl text-xs font-mono text-emerald-400 overflow-x-auto whitespace-pre-wrap leading-relaxed border border-slate-800">
            {NFC_TABLE_SQL}
          </pre>
        </div>
      )}

      {/* Feedback Message */}
      {message && (
        <div
          className={`p-4 rounded-xl text-sm flex items-start gap-3 shadow-sm border ${
            message.type === "success"
              ? "bg-emerald-50 text-emerald-800 border-emerald-200"
              : message.type === "error"
              ? "bg-red-50 text-red-800 border-red-200"
              : "bg-blue-50 text-blue-800 border-blue-200"
          }`}
        >
          {message.type === "success" ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
          ) : message.type === "error" ? (
            <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
          ) : (
            <Info className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
          )}
          <div className="flex-1 font-medium">{message.text}</div>
        </div>
      )}

      {/* Workflow Step Forms */}
      <form onSubmit={handleSaveNFC} className="space-y-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* STEP 1: Tap / Scan Kartu NFC */}
          <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="w-6 h-6 rounded-full bg-[#203598] text-white text-xs font-bold flex items-center justify-center">
                  1
                </span>
                <h3 className="font-bold text-slate-800 text-base">Tap Kartu NFC ke Perangkat</h3>
              </div>
              <p className="text-xs text-slate-500 mb-4">
                Tempelkan kartu NFC ke sensor perangkat Anda untuk membaca Serial Number (UID) kartu secara otomatis.
              </p>

              {/* NFC Sensor Reader Visual Box */}
              <div className="bg-slate-50 rounded-xl p-5 border border-slate-200 text-center flex flex-col items-center justify-center space-y-3">
                <div
                  className={`w-16 h-16 rounded-full flex items-center justify-center transition-all ${
                    isScanning
                      ? "bg-blue-100 text-[#203598] animate-pulse ring-4 ring-blue-200"
                      : scannedUID
                      ? "bg-emerald-100 text-emerald-600"
                      : "bg-slate-200 text-slate-500"
                  }`}
                >
                  <Nfc className="w-8 h-8" />
                </div>

                {isScanning ? (
                  <div className="space-y-1">
                    <p className="text-sm font-bold text-[#203598]">Menunggu Kartu NFC...</p>
                    <p className="text-xs text-slate-500">Tempelkan kartu ke bagian belakang HP/Perangkat</p>
                    <button
                      type="button"
                      onClick={stopScan}
                      className="mt-2 text-xs font-semibold text-red-600 hover:underline"
                    >
                      Batal Scan
                    </button>
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={handleScanNFC}
                    className="px-4 py-2 bg-[#203598] hover:bg-[#1a2c7d] text-white rounded-xl text-xs font-semibold shadow-md transition-all flex items-center gap-2"
                  >
                    <Nfc className="w-4 h-4" />
                    Mulai Scan Kartu NFC
                  </button>
                )}
              </div>
            </div>

            {/* Input Manual UID / Display Scanned UID */}
            <div className="space-y-1.5 pt-2 border-t border-slate-100">
              <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block">
                Serial Number / UID Kartu NFC
              </label>
              <input
                type="text"
                value={scannedUID}
                onChange={(e) => setScannedUID(e.target.value.toUpperCase())}
                placeholder="Contoh: 04:A2:B3:C4:D5"
                required
                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl font-mono text-slate-800 text-sm font-semibold tracking-widest focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
              />
              <p className="text-[11px] text-slate-400">
                UID akan terisi otomatis saat ditempelkan ke sensor NFC, atau Anda dapat mengetiknya manual.
              </p>
            </div>
          </div>

          {/* STEP 2: Pilih Nama Peserta */}
          <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="w-6 h-6 rounded-full bg-[#203598] text-white text-xs font-bold flex items-center justify-center">
                  2
                </span>
                <h3 className="font-bold text-slate-800 text-base">Pilih Nama Peserta</h3>
              </div>
              <p className="text-xs text-slate-500 mb-3">
                Ketik nama peserta untuk mencari dari daftar peserta terdaftar.
              </p>

              {/* Search input for peserta */}
              <div className="relative mb-3">
                <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Ketik nama peserta..."
                  className="w-full pl-10 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                />
              </div>

              {/* Peserta Selection Box List */}
              <div className="border border-slate-200 rounded-xl max-h-48 overflow-y-auto divide-y divide-slate-100 bg-slate-50/50">
                {loadingPeserta ? (
                  <div className="p-4 text-center text-xs text-slate-400 flex items-center justify-center gap-2">
                    <RefreshCw className="w-4 h-4 animate-spin text-[#203598]" />
                    Memuat data peserta...
                  </div>
                ) : filteredPeserta.length === 0 ? (
                  <div className="p-4 text-center text-xs text-slate-400">
                    Tidak ditemukan peserta dengan kata kunci &quot;{searchTerm}&quot;.
                  </div>
                ) : (
                  filteredPeserta.map((p) => {
                    const isSelected = selectedPeserta?.id === p.id;
                    return (
                      <button
                        key={p.id}
                        type="button"
                        onClick={() => setSelectedPeserta(p)}
                        className={`w-full px-4 py-2.5 text-left text-xs flex items-center justify-between transition-colors ${
                          isSelected
                            ? "bg-[#203598] text-white font-semibold"
                            : "hover:bg-slate-100 text-slate-700"
                        }`}
                      >
                        <div>
                          <div className="font-bold text-sm">{p.nama}</div>
                          <div className={`text-[11px] ${isSelected ? "text-blue-100" : "text-slate-400"}`}>
                            Kelompok: {p.kelompok || "-"}
                          </div>
                        </div>
                        {isSelected && <Check className="w-4 h-4 text-white shrink-0" />}
                      </button>
                    );
                  })
                )}
              </div>
            </div>

            {/* Selected Peserta Card Preview */}
            <div className="pt-2 border-t border-slate-100">
              <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                Peserta Terpilih
              </label>
              {selectedPeserta ? (
                <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl flex items-center justify-between">
                  <div>
                    <div className="font-bold text-sm text-emerald-900">{selectedPeserta.nama}</div>
                    <div className="text-xs text-emerald-700">Kelompok: {selectedPeserta.kelompok || "-"}</div>
                  </div>
                  <UserCheck className="w-5 h-5 text-emerald-600 shrink-0" />
                </div>
              ) : (
                <div className="p-3 bg-slate-100 border border-slate-200 rounded-xl text-xs text-slate-500 italic text-center">
                  Belum ada peserta terpilih. Pilih nama peserta di atas.
                </div>
              )}
            </div>
          </div>
        </div>

        {/* STEP 3: Save Button */}
        <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <span className="w-6 h-6 rounded-full bg-[#203598] text-white text-xs font-bold flex items-center justify-center">
              3
            </span>
            <span className="font-bold text-slate-800 text-sm">Simpan Hubungan NFC &amp; Peserta</span>
          </div>

          <button
            type="submit"
            disabled={saving || !scannedUID.trim() || !selectedPeserta}
            className="px-6 py-3 bg-[#203598] hover:bg-[#1a2c7d] text-white font-semibold rounded-xl shadow-md shadow-[#203598]/20 transition-all active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 text-sm"
          >
            {saving ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                Menyimpan...
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                Simpan Data NFC
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
