"use client";

import { useState, useEffect, useCallback } from "react";
import { Nfc, Search, Check, Save, AlertCircle, CheckCircle2, Copy, RefreshCw, UserCheck, Database, Code, Info, Smartphone, HelpCircle } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { hexToDecimal, toTitleCase } from "@/lib/utils";

interface Peserta {
  id: number;
  nama: string;
  kelompok: string;
  dapukan?: string;
  tenda?: string;
  grup_fgd?: string;
  foto?: string | null;
  foto_url?: string | null;
}

const NFC_TABLE_SQL = `-- Skrip SQL untuk membuat tabel 'nfc_peserta' di Supabase
-- Jalankan di Supabase Dashboard > SQL Editor > Run

CREATE TABLE IF NOT EXISTS public.nfc_peserta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nfc_uid TEXT UNIQUE NOT NULL,
  peserta_id BIGINT REFERENCES public.peserta(id) ON DELETE CASCADE,
  nama TEXT NOT NULL,
  kelompok TEXT DEFAULT '-',
  dapukan TEXT DEFAULT '-',
  tenda TEXT DEFAULT '-',
  grup_fgd TEXT DEFAULT '-'
);

-- Tambahkan kolom jika tabel nfc_peserta sudah pernah dibuat sebelumnya:
ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS dapukan TEXT DEFAULT '-';
ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS tenda TEXT DEFAULT '-';
ALTER TABLE public.nfc_peserta ADD COLUMN IF NOT EXISTS grup_fgd TEXT DEFAULT '-';

-- Aktifkan RLS dan Kebijakan Akses Penuh
ALTER TABLE public.nfc_peserta ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access nfc_peserta" ON public.nfc_peserta;
CREATE POLICY "Allow full access nfc_peserta"
ON public.nfc_peserta
FOR ALL
USING (true)
WITH CHECK (true);`;

export default function InputNFCPesertaForm() {
  const [scannedUID, setScannedUID] = useState<string>("");
  const [isScanning, setIsScanning] = useState(false);
  const [isSupported, setIsSupported] = useState<boolean | null>(null);

  const [pesertaList, setPesertaList] = useState<Peserta[]>([]);
  const [loadingPeserta, setLoadingPeserta] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedPeserta, setSelectedPeserta] = useState<Peserta | null>(null);

  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error" | "info"; text: string } | null>(null);
  const [copiedSql, setCopiedSql] = useState(false);
  const [showSql, setShowSql] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setIsSupported("NDEFReader" in window);
    }
    fetchPeserta();
  }, []);

  const fetchPeserta = async () => {
    setLoadingPeserta(true);
    try {
      const { data, error } = await supabase
        .from("peserta")
        .select("*")
        .order("nama", { ascending: true });

      if (error) {
        console.error("Error fetching peserta:", error);
      } else {
        const formatted: Peserta[] = (data || []).map((p: any) => ({
          ...p,
          nama: toTitleCase(p.nama || p.nama_peserta || ""),
          kelompok: p.kelompok ? toTitleCase(p.kelompok) : "-",
          dapukan: p.dapukan ? toTitleCase(p.dapukan) : "-",
          tenda: (p.tenda || p.grup) ? toTitleCase(p.tenda || p.grup) : "-",
          grup_fgd: p.grup_fgd ? toTitleCase(p.grup_fgd) : "-",
          foto: p.foto || p.foto_url || null,
          foto_url: p.foto || p.foto_url || null,
        }));
        setPesertaList(formatted);
      }
    } catch (err) {
      console.error("Error fetching peserta:", err);
    } finally {
      setLoadingPeserta(false);
    }
  };

  const handleScanNFC = useCallback(async () => {
    if (!("NDEFReader" in window)) {
      setMessage({
        type: "error",
        text: "Browser/Perangkat tidak mendukung Web NFC. Anda juga dapat mengetik UID kartu secara manual.",
      });
      return;
    }

    try {
      setIsScanning(true);
      setMessage({
        type: "info",
        text: "Sensor NFC Android aktif! Silakan tempelkan kartu NFC ke bagian belakang HP Anda...",
      });

      // @ts-ignore
      const ndef = new window.NDEFReader();
      await ndef.scan();

      ndef.addEventListener("reading", (event: any) => {
        let rawUid = event.serialNumber || "";
        if (!rawUid && event.message?.records) {
          for (const record of event.message.records) {
            if (record.data) {
              try {
                const textDecoder = new TextDecoder(record.encoding || "utf-8");
                const decoded = textDecoder.decode(record.data).trim();
                if (decoded) {
                  rawUid = decoded;
                  break;
                }
              } catch (e) {}
            }
          }
        }

        if (rawUid) {
          const formattedUID = hexToDecimal(rawUid, true);
          setScannedUID(formattedUID);
          setIsScanning(false);
          setMessage({
            type: "success",
            text: `Kartu NFC terdeteksi! UID: ${formattedUID} (Raw: ${rawUid})`,
          });

          if (typeof navigator !== "undefined" && navigator.vibrate) {
            navigator.vibrate(200);
          }
        }
      });

      ndef.addEventListener("readingerror", () => {
        setMessage({
          type: "error",
          text: "Gagal membaca tag NFC. Pastikan kartu menempel erat di belakang HP dekat kamera.",
        });
      });
    } catch (error: any) {
      setIsScanning(false);
      if (error.name === "NotAllowedError") {
        setMessage({
          type: "error",
          text: "Izin sensor NFC ditolak. Buka website di tab baru Google Chrome dan izinkan akses NFC.",
        });
      } else {
        setMessage({
          type: "error",
          text: `Gagal mengaktifkan sensor NFC: ${error.message || error}`,
        });
      }
    }
  }, []);

  const stopScan = () => {
    setIsScanning(false);
    setMessage(null);
  };

  const handleSaveNFC = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!scannedUID.trim()) {
      setMessage({ type: "error", text: "UID Kartu NFC belum ada. Tap kartu terlebih dahulu atau ketik UID manual." });
      return;
    }
    if (!selectedPeserta) {
      setMessage({ type: "error", text: "Silakan pilih nama peserta terlebih dahulu." });
      return;
    }

    setSaving(true);
    setMessage(null);

    const uidClean = hexToDecimal(scannedUID.trim(), true) || scannedUID.trim();
    
    // Variasi UID untuk penanganan awalan 00 (misal 0085926167 vs 85926167)
    const uidVariations = Array.from(
      new Set([
        uidClean,
        uidClean.toLowerCase(),
        uidClean.toUpperCase(),
        uidClean.replace(/^0+/, ""),
        uidClean.padStart(10, "0"),
        scannedUID.trim(),
      ])
    ).filter(Boolean);

    const basePayload: any = {
      nfc_uid: uidClean,
      peserta_id: selectedPeserta.id,
      nama: selectedPeserta.nama,
      kelompok: selectedPeserta.kelompok || "-",
      dapukan: selectedPeserta.dapukan || "-",
      tenda: selectedPeserta.tenda || "-",
      grup: selectedPeserta.tenda || "-",
      grup_fgd: selectedPeserta.grup_fgd || "-",
    };

    try {
      // 1. Cek apakah kartu NFC atau Peserta sudah pernah terdaftar di nfc_peserta
      let matchedId: number | null = null;
      try {
        const { data: existingNfc } = await supabase
          .from("nfc_peserta")
          .select("id, nfc_uid, peserta_id, nama")
          .in("nfc_uid", uidVariations);

        if (existingNfc && existingNfc.length > 0) {
          matchedId = existingNfc[0].id;
        } else {
          const { data: existingByPeserta } = await supabase
            .from("nfc_peserta")
            .select("id, nfc_uid, peserta_id, nama")
            .eq("peserta_id", selectedPeserta.id);

          if (existingByPeserta && existingByPeserta.length > 0) {
            matchedId = existingByPeserta[0].id;
          }
        }
      } catch (checkErr) {
        console.warn("Cek data nfc_peserta sebelumnya:", checkErr);
      }

      // 2. Simpan ke tabel nfc_peserta (Update jika sudah ada, atau Insert jika baru)
      let saveSuccess = false;

      if (matchedId) {
        // Mode UPDATE berdasarkan ID existing (mencegah error 23505 duplicate key)
        const { error: updErr } = await supabase
          .from("nfc_peserta")
          .update(basePayload)
          .eq("id", matchedId);

        if (!updErr) {
          saveSuccess = true;
        } else if (updErr.code === "42703" || updErr.message?.includes("does not exist")) {
          // Fallback tanpa kolom tenda (pakai grup)
          const payloadGrup = { ...basePayload };
          delete payloadGrup.tenda;
          const { error: updGrupErr } = await supabase
            .from("nfc_peserta")
            .update(payloadGrup)
            .eq("id", matchedId);

          if (!updGrupErr) {
            saveSuccess = true;
          } else {
            // Fallback kolom minimal
            const payloadCore = {
              nfc_uid: uidClean,
              peserta_id: selectedPeserta.id,
              nama: selectedPeserta.nama,
              kelompok: selectedPeserta.kelompok || "-",
            };
            const { error: updCoreErr } = await supabase
              .from("nfc_peserta")
              .update(payloadCore)
              .eq("id", matchedId);
            if (!updCoreErr) saveSuccess = true;
          }
        }
      }

      if (!saveSuccess) {
        // Coba Upsert dengan onConflict
        let { error: upsertErr } = await supabase
          .from("nfc_peserta")
          .upsert([basePayload], { onConflict: "nfc_uid" });

        if (!upsertErr) {
          saveSuccess = true;
        } else {
          // Jika error kolom tidak ada (42703)
          if (upsertErr.code === "42703" || upsertErr.message?.includes("does not exist")) {
            const payloadGrup = { ...basePayload };
            delete payloadGrup.tenda;
            const resGrup = await supabase
              .from("nfc_peserta")
              .upsert([payloadGrup], { onConflict: "nfc_uid" });
            if (!resGrup.error) {
              saveSuccess = true;
            } else {
              const payloadCore = {
                nfc_uid: uidClean,
                peserta_id: selectedPeserta.id,
                nama: selectedPeserta.nama,
                kelompok: selectedPeserta.kelompok || "-",
              };
              const resCore = await supabase
                .from("nfc_peserta")
                .upsert([payloadCore], { onConflict: "nfc_uid" });
              if (!resCore.error) saveSuccess = true;
            }
          }

          // Jika masih belum berhasil atau kena duplicate key constraint, coba update langsung by nfc_uid
          if (!saveSuccess) {
            const { error: directUpdErr } = await supabase
              .from("nfc_peserta")
              .update(basePayload)
              .in("nfc_uid", uidVariations);

            if (!directUpdErr) {
              saveSuccess = true;
            } else {
              // Terakhir coba insert murni
              const { error: insErr } = await supabase
                .from("nfc_peserta")
                .insert([basePayload]);

              if (!insErr) {
                saveSuccess = true;
              } else if (insErr.code === "23505" || insErr.message?.includes("duplicate key")) {
                // Tangani duplicate key secara elegan dengan update by nfc_uid
                const payloadCore = {
                  peserta_id: selectedPeserta.id,
                  nama: selectedPeserta.nama,
                  kelompok: selectedPeserta.kelompok || "-",
                  dapukan: selectedPeserta.dapukan || "-",
                };
                await supabase
                  .from("nfc_peserta")
                  .update(payloadCore)
                  .in("nfc_uid", uidVariations);
                saveSuccess = true;
              } else {
                throw insErr;
              }
            }
          }
        }
      }

      // 3. Sinkronkan juga UID kartu ke tabel 'peserta' utama
      try {
        const { error: pUpdErr } = await supabase
          .from("peserta")
          .update({
            nfc_uid: uidClean,
            smartcard: uidClean,
            uid_nfc: uidClean,
            serial_number: uidClean,
          })
          .eq("id", selectedPeserta.id);

        if (pUpdErr) {
          // Fallback tanpa nfc_uid / uid_nfc jika kolom berbeda
          await supabase
            .from("peserta")
            .update({ smartcard: uidClean })
            .eq("id", selectedPeserta.id);
        }
      } catch (pErr) {
        console.warn("Update smartcard ke tabel peserta:", pErr);
      }

      // 4. Update Local Storage Cache untuk offline & instant scanning
      try {
        if (typeof window !== "undefined") {
          const localStr = localStorage.getItem("cai_peserta");
          if (localStr) {
            const list = JSON.parse(localStr);
            if (Array.isArray(list)) {
              const updated = list.map((item: any) =>
                item.id === selectedPeserta.id
                  ? { ...item, nfc_uid: uidClean, smartcard: uidClean, uid_nfc: uidClean }
                  : item
              );
              localStorage.setItem("cai_peserta", JSON.stringify(updated));
            }
          }
        }
      } catch (lsErr) {}

      setMessage({
        type: "success",
        text: `Berhasil menyimpan data NFC! Kartu [${uidClean}] terhubung dengan "${selectedPeserta.nama}" (${selectedPeserta.kelompok}).`,
      });

      // Reset selection
      setScannedUID("");
      setSelectedPeserta(null);
      setSearchTerm("");
    } catch (err: any) {
      console.error("Error saving NFC peserta:", err);
      let detail = err.message || "Gagal menyimpan data NFC peserta.";
      if (err.code === "42P01" || detail.toLowerCase().includes("does not exist")) {
        detail = "Tabel 'nfc_peserta' belum dibuat di Supabase. Silakan jalankan Kode SQL di bawah untuk membuat tabelnya.";
        setShowSql(true);
      } else if (err.code === "42501" || detail.toLowerCase().includes("row-level security")) {
        detail = "Akses ditolak oleh RLS Supabase pada tabel 'nfc_peserta'. Jalankan skrip SQL di bawah untuk mengaktifkan kebijakan RLS.";
        setShowSql(true);
      }
      setMessage({ type: "error", text: detail });
    } finally {
      setSaving(false);
    }
  };

  const copySqlCode = () => {
    navigator.clipboard.writeText(NFC_TABLE_SQL);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  const filteredPeserta = pesertaList.filter((p) => {
    const term = searchTerm.toLowerCase();
    return (
      p.nama.toLowerCase().includes(term) ||
      (p.kelompok && p.kelompok.toLowerCase().includes(term)) ||
      (p.dapukan && p.dapukan.toLowerCase().includes(term)) ||
      (p.tenda && p.tenda.toLowerCase().includes(term)) ||
      (p.grup_fgd && p.grup_fgd.toLowerCase().includes(term))
    );
  });

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Page Title Header */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Nfc className="w-6 h-6 text-[#203598]" />
            Input Data NFC Peserta
          </h2>
          <p className="text-slate-500 text-xs mt-1">
            Hubungkan kartu fisik NFC dengan nama peserta terdaftar.
          </p>
        </div>
        <button
          onClick={() => setShowSql(!showSql)}
          className="px-3 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-2 transition-colors border border-slate-200"
        >
          <Code className="w-4 h-4 text-[#203598]" />
          {showSql ? "Sembunyikan Kode SQL" : "Kode SQL Tabel NFC"}
        </button>
      </div>

      {/* SQL Script Card (Toggleable) */}
      {showSql && (
        <div className="bg-slate-900 text-slate-100 rounded-2xl p-6 shadow-xl border border-slate-800 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm">
              <Database className="w-5 h-5" />
              <span>Kode SQL Tabel &apos;nfc_peserta&apos;</span>
            </div>
            <button
              onClick={copySqlCode}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors border border-slate-700"
            >
              {copiedSql ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  Tersalin!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Salin SQL
                </>
              )}
            </button>
          </div>
          <p className="text-xs text-slate-400">
            Jalankan skrip ini di <strong>Supabase Dashboard &gt; SQL Editor &gt; Run</strong> untuk membuat tabel nfc_peserta.
          </p>
          <pre className="bg-black/50 p-4 rounded-xl text-xs font-mono text-emerald-400 overflow-x-auto whitespace-pre-wrap leading-relaxed border border-slate-800">
            {NFC_TABLE_SQL}
          </pre>
        </div>
      )}

      {/* Feedback Message */}
      {message && (
        <div
          className={`p-4 rounded-xl text-sm flex items-start gap-3 shadow-sm border ${
            message.type === "success"
              ? "bg-emerald-50 text-emerald-800 border-emerald-200"
              : message.type === "error"
              ? "bg-red-50 text-red-800 border-red-200"
              : "bg-blue-50 text-blue-800 border-blue-200"
          }`}
        >
          {message.type === "success" ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
          ) : message.type === "error" ? (
            <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
          ) : (
            <Info className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
          )}
          <div className="flex-1 font-medium">{message.text}</div>
        </div>
      )}

      {/* Workflow Step Forms */}
      <form onSubmit={handleSaveNFC} className="space-y-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* STEP 1: Tap / Scan Kartu NFC */}
          <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="w-6 h-6 rounded-full bg-[#203598] text-white text-xs font-bold flex items-center justify-center">
                  1
                </span>
                <h3 className="font-bold text-slate-800 text-base">Tap Kartu NFC ke Perangkat</h3>
              </div>
              <p className="text-xs text-slate-500 mb-4">
                Tempelkan kartu NFC ke sensor perangkat Anda untuk membaca Serial Number (UID) kartu secara otomatis.
              </p>

              {/* NFC Sensor Reader Visual Box */}
              <div className="bg-slate-50 rounded-xl p-5 border border-slate-200 text-center flex flex-col items-center justify-center space-y-3">
                <div
                  className={`w-16 h-16 rounded-full flex items-center justify-center transition-all ${
                    isScanning
                      ? "bg-blue-100 text-[#203598] animate-pulse ring-4 ring-blue-200"
                      : scannedUID
                      ? "bg-emerald-100 text-emerald-600"
                      : "bg-slate-200 text-slate-500"
                  }`}
                >
                  <Nfc className="w-8 h-8" />
                </div>

                {isScanning ? (
                  <div className="space-y-1.5 w-full">
                    <p className="text-sm font-bold text-[#203598]">Sensor NFC Android Aktif...</p>
                    <p className="text-xs text-slate-500">Tempelkan kartu ke bagian belakang HP Android Anda</p>
                    <button
                      type="button"
                      onClick={stopScan}
                      className="mt-1 px-3 py-1.5 bg-rose-50 text-rose-700 hover:bg-rose-100 rounded-lg text-xs font-bold transition-colors cursor-pointer"
                    >
                      Hentikan Scan
                    </button>
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={handleScanNFC}
                    className="w-full px-4 py-2.5 bg-[#203598] hover:bg-[#182a7a] active:bg-[#121f5c] text-white rounded-xl text-xs sm:text-sm font-bold shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer active:scale-98"
                  >
                    <Smartphone className="w-4 h-4 text-emerald-300" />
                    <span>Mulai Tap NFC di Android</span>
                  </button>
                )}
              </div>
            </div>

            {/* Input Manual UID / Display Scanned UID */}
            <div className="space-y-1.5 pt-2 border-t border-slate-100">
              <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block">
                Serial Number / UID Kartu NFC
              </label>
              <input
                type="text"
                value={scannedUID}
                onChange={(e) => setScannedUID(e.target.value.toUpperCase())}
                placeholder="Contoh: 04:A2:B3:C4:D5"
                required
                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl font-mono text-slate-800 text-sm font-semibold tracking-widest focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
              />
              <p className="text-[11px] text-slate-400">
                UID akan terisi otomatis saat ditempelkan ke sensor NFC, atau Anda dapat mengetiknya manual.
              </p>
            </div>
          </div>

          {/* STEP 2: Pilih Nama Peserta */}
          <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="w-6 h-6 rounded-full bg-[#203598] text-white text-xs font-bold flex items-center justify-center">
                  2
                </span>
                <h3 className="font-bold text-slate-800 text-base">Pilih Nama Peserta</h3>
              </div>
              <p className="text-xs text-slate-500 mb-3">
                Ketik nama peserta untuk mencari dari daftar peserta terdaftar.
              </p>

              {/* Search input for peserta */}
              <div className="relative mb-3">
                <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Ketik nama peserta..."
                  className="w-full pl-10 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                />
              </div>

              {/* Peserta Selection Box List */}
              <div className="border border-slate-200 rounded-xl max-h-48 overflow-y-auto divide-y divide-slate-100 bg-slate-50/50">
                {loadingPeserta ? (
                  <div className="p-4 text-center text-xs text-slate-400 flex items-center justify-center gap-2">
                    <RefreshCw className="w-4 h-4 animate-spin text-[#203598]" />
                    Memuat data peserta...
                  </div>
                ) : filteredPeserta.length === 0 ? (
                  <div className="p-4 text-center text-xs text-slate-400">
                    Tidak ditemukan peserta dengan kata kunci &quot;{searchTerm}&quot;.
                  </div>
                ) : (
                  filteredPeserta.map((p) => {
                    const isSelected = selectedPeserta?.id === p.id;
                    const photoSrc = p.foto || p.foto_url;
                    return (
                      <button
                        key={p.id}
                        type="button"
                        onClick={() => setSelectedPeserta(p)}
                        className={`w-full px-4 py-2.5 text-left text-xs flex items-center justify-between gap-3 transition-colors ${
                          isSelected
                            ? "bg-[#203598] text-white font-semibold"
                            : "hover:bg-slate-100 text-slate-700"
                        }`}
                      >
                        <div className="flex items-center gap-3 min-w-0">
                          <div className={`w-8 h-8 rounded-lg overflow-hidden shrink-0 flex items-center justify-center font-bold text-xs ${
                            isSelected ? "bg-white/20 text-white" : "bg-slate-200 text-slate-700"
                          }`}>
                            {photoSrc ? (
                              <img src={photoSrc} alt={p.nama} className="w-full h-full object-cover" />
                            ) : (
                              <span>{p.nama.charAt(0).toUpperCase()}</span>
                            )}
                          </div>
                          <div className="truncate">
                            <div className="font-bold text-sm truncate">{p.nama}</div>
                            <div className={`text-[11px] flex flex-wrap items-center gap-2 mt-0.5 ${isSelected ? "text-blue-100" : "text-slate-500"}`}>
                              <span>Kelompok: {p.kelompok || "-"}</span>
                              {p.dapukan && p.dapukan !== "-" && <span>• Dapukan: {p.dapukan}</span>}
                              {p.tenda && p.tenda !== "-" && <span>• Tenda: {p.tenda}</span>}
                              {p.grup_fgd && p.grup_fgd !== "-" && <span>• FGD: {p.grup_fgd}</span>}
                            </div>
                          </div>
                        </div>
                        {isSelected && <Check className="w-4 h-4 text-white shrink-0" />}
                      </button>
                    );
                  })
                )}
              </div>
            </div>

            {/* Selected Peserta Card Preview */}
            <div className="pt-2 border-t border-slate-100">
              <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                Peserta Terpilih
              </label>
              {selectedPeserta ? (
                <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl flex items-center justify-between gap-3">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl overflow-hidden bg-emerald-200 flex items-center justify-center font-bold text-emerald-800 text-sm shrink-0 border border-emerald-300">
                      {(selectedPeserta.foto || selectedPeserta.foto_url) ? (
                        <img
                          src={selectedPeserta.foto || selectedPeserta.foto_url || ""}
                          alt={selectedPeserta.nama}
                          className="w-full h-full object-cover"
                        />
                      ) : (
                        <span>{selectedPeserta.nama.charAt(0).toUpperCase()}</span>
                      )}
                    </div>
                    <div>
                      <div className="font-bold text-sm text-emerald-900">{selectedPeserta.nama}</div>
                      <div className="text-xs text-emerald-700 flex flex-wrap gap-2 mt-1">
                        <span className="font-medium">Kelompok: {selectedPeserta.kelompok || "-"}</span>
                        {selectedPeserta.dapukan && selectedPeserta.dapukan !== "-" && (
                          <span className="px-1.5 py-0.5 bg-emerald-100/80 text-emerald-800 rounded text-[10px]">
                            Dapukan: {selectedPeserta.dapukan}
                          </span>
                        )}
                        {selectedPeserta.tenda && selectedPeserta.tenda !== "-" && (
                          <span className="px-1.5 py-0.5 bg-emerald-100/80 text-emerald-800 rounded text-[10px]">
                            Tenda: {selectedPeserta.tenda}
                          </span>
                        )}
                        {selectedPeserta.grup_fgd && selectedPeserta.grup_fgd !== "-" && (
                          <span className="px-1.5 py-0.5 bg-emerald-100/80 text-emerald-800 rounded text-[10px]">
                            FGD: {selectedPeserta.grup_fgd}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <UserCheck className="w-5 h-5 text-emerald-600 shrink-0" />
                </div>
              ) : (
                <div className="p-3 bg-slate-100 border border-slate-200 rounded-xl text-xs text-slate-500 italic text-center">
                  Belum ada peserta terpilih. Pilih nama peserta di atas.
                </div>
              )}
            </div>
          </div>
        </div>

        {/* STEP 3: Save Button */}
        <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <span className="w-6 h-6 rounded-full bg-[#203598] text-white text-xs font-bold flex items-center justify-center">
              3
            </span>
            <span className="font-bold text-slate-800 text-sm">Simpan Hubungan NFC &amp; Peserta</span>
          </div>

          <button
            type="submit"
            disabled={saving || !scannedUID.trim() || !selectedPeserta}
            className="px-6 py-3 bg-[#203598] hover:bg-[#1a2c7d] text-white font-semibold rounded-xl shadow-md shadow-[#203598]/20 transition-all active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 text-sm"
          >
            {saving ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                Menyimpan...
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                Simpan Data NFC
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
