"use client";

import { useState, useEffect, useCallback } from "react";
import {
  Clock,
  Plus,
  Trash2,
  Edit,
  Check,
  CheckCircle2,
  XCircle,
  Copy,
  Code,
  Database,
  Info,
  RefreshCw,
  AlertCircle,
  Calendar,
  Sparkles,
  ToggleLeft,
  ToggleRight
} from "lucide-react";
import { supabase } from "@/lib/supabase";

export interface SesiAbsensi {
  id: number;
  nama_sesi: string;
  tanggal: string; // YYYY-MM-DD
  jam_mulai: string; // HH:mm
  jam_selesai: string; // HH:mm
  is_active: boolean;
  keterangan?: string;
}

const SESI_SQL_CODE = `-- Skrip SQL untuk membuat tabel 'sesi_absensi' di Supabase
-- Jalankan di Supabase Dashboard > SQL Editor > Run

CREATE TABLE IF NOT EXISTS public.sesi_absensi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nama_sesi TEXT NOT NULL,
  tanggal DATE NOT NULL,
  jam_mulai TIME NOT NULL,
  jam_selesai TIME NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  keterangan TEXT DEFAULT ''
);

-- Aktifkan RLS dan Kebijakan Akses Penuh
ALTER TABLE public.sesi_absensi ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access sesi_absensi" ON public.sesi_absensi;
CREATE POLICY "Allow full access sesi_absensi"
ON public.sesi_absensi
FOR ALL
USING (true)
WITH CHECK (true);`;

export default function ManajemenSesi() {
  const [sesiList, setSesiList] = useState<SesiAbsensi[]>([]);
  const [loading, setLoading] = useState(true);
  const [showSql, setShowSql] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error" | "info"; text: string } | null>(null);

  // Form State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingSesi, setEditingSesi] = useState<SesiAbsensi | null>(null);
  
  const getTodayString = () => {
    const today = new Date();
    return today.toISOString().split("T")[0];
  };

  const [formNamaSesi, setFormNamaSesi] = useState("");
  const [formTanggal, setFormTanggal] = useState(getTodayString());
  const [formJamMulai, setFormJamMulai] = useState("08:00");
  const [formJamSelesai, setFormJamSelesai] = useState("11:30");
  const [formIsActive, setFormIsActive] = useState(true);
  const [formKeterangan, setFormKeterangan] = useState("");
  const [saving, setSaving] = useState(false);

  const fetchSesiList = useCallback(async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from("sesi_absensi")
        .select("*")
        .order("tanggal", { ascending: false })
        .order("jam_mulai", { ascending: true });

      if (error) {
        console.warn("Supabase sesi_absensi error / table not found:", error);
        // Fallback local storage
        const localData = localStorage.getItem("cai_sesi_absensi");
        if (localData) {
          setSesiList(JSON.parse(localData));
        } else {
          // Sample default session
          const defaultSample: SesiAbsensi[] = [
            {
              id: 1,
              nama_sesi: "Sesi Pagi - Materi CAI",
              tanggal: getTodayString(),
              jam_mulai: "07:30",
              jam_selesai: "12:00",
              is_active: true,
              keterangan: "Absensi kehadiran materi sesi pagi",
            },
            {
              id: 2,
              nama_sesi: "Sesi Siang - Diskusi Kelompok",
              tanggal: getTodayString(),
              jam_mulai: "13:00",
              jam_selesai: "16:00",
              is_active: true,
              keterangan: "Absensi kelompok diskusi siang",
            },
          ];
          setSesiList(defaultSample);
          localStorage.setItem("cai_sesi_absensi", JSON.stringify(defaultSample));
        }
      } else {
        setSesiList(data || []);
      }
    } catch (err) {
      console.error("Error fetching sesi:", err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchSesiList();
  }, [fetchSesiList]);

  const openAddModal = () => {
    setEditingSesi(null);
    setFormNamaSesi("");
    setFormTanggal(getTodayString());
    setFormJamMulai("08:00");
    setFormJamSelesai("11:30");
    setFormIsActive(true);
    setFormKeterangan("");
    setIsModalOpen(true);
  };

  const openEditModal = (sesi: SesiAbsensi) => {
    setEditingSesi(sesi);
    setFormNamaSesi(sesi.nama_sesi);
    setFormTanggal(sesi.tanggal);
    setFormJamMulai(sesi.jam_mulai.slice(0, 5));
    setFormJamSelesai(sesi.jam_selesai.slice(0, 5));
    setFormIsActive(sesi.is_active);
    setFormKeterangan(sesi.keterangan || "");
    setIsModalOpen(true);
  };

  const handleSaveSesi = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formNamaSesi.trim()) {
      setMessage({ type: "error", text: "Nama sesi wajib diisi." });
      return;
    }

    setSaving(true);
    setMessage(null);

    const payload = {
      nama_sesi: formNamaSesi.trim(),
      tanggal: formTanggal,
      jam_mulai: formJamMulai,
      jam_selesai: formJamSelesai,
      is_active: formIsActive,
      keterangan: formKeterangan.trim(),
    };

    try {
      if (editingSesi) {
        // Update
        const { error } = await supabase
          .from("sesi_absensi")
          .update(payload)
          .eq("id", editingSesi.id);

        if (error) {
          // Fallback local storage
          const updated = sesiList.map((s) => (s.id === editingSesi.id ? { ...s, ...payload } : s));
          setSesiList(updated);
          localStorage.setItem("cai_sesi_absensi", JSON.stringify(updated));
        } else {
          await fetchSesiList();
        }
        setMessage({ type: "success", text: `Sesi "${formNamaSesi}" berhasil diperbarui.` });
      } else {
        // Insert
        const { error } = await supabase.from("sesi_absensi").insert([payload]);

        if (error) {
          // Fallback local storage
          const newItem: SesiAbsensi = {
            id: Date.now(),
            ...payload,
          };
          const updated = [newItem, ...sesiList];
          setSesiList(updated);
          localStorage.setItem("cai_sesi_absensi", JSON.stringify(updated));
        } else {
          await fetchSesiList();
        }
        setMessage({ type: "success", text: `Sesi "${formNamaSesi}" berhasil ditambahkan.` });
      }

      setIsModalOpen(false);
    } catch (err: any) {
      console.error("Error saving sesi:", err);
      setMessage({ type: "error", text: err.message || "Gagal menyimpan sesi." });
    } finally {
      setSaving(false);
    }
  };

  const handleDeleteSesi = async (id: number, nama: string) => {
    if (!confirm(`Apakah Anda yakin ingin menghapus sesi "${nama}"?`)) return;

    try {
      const { error } = await supabase.from("sesi_absensi").delete().eq("id", id);
      if (error) {
        const updated = sesiList.filter((s) => s.id !== id);
        setSesiList(updated);
        localStorage.setItem("cai_sesi_absensi", JSON.stringify(updated));
      } else {
        await fetchSesiList();
      }
      setMessage({ type: "success", text: `Sesi "${nama}" telah dihapus.` });
    } catch (err) {
      console.error("Error deleting sesi:", err);
    }
  };

  const handleToggleActive = async (sesi: SesiAbsensi) => {
    const updatedStatus = !sesi.is_active;
    try {
      const { error } = await supabase
        .from("sesi_absensi")
        .update({ is_active: updatedStatus })
        .eq("id", sesi.id);

      if (error) {
        const updated = sesiList.map((s) => (s.id === sesi.id ? { ...s, is_active: updatedStatus } : s));
        setSesiList(updated);
        localStorage.setItem("cai_sesi_absensi", JSON.stringify(updated));
      } else {
        await fetchSesiList();
      }
    } catch (err) {
      console.error("Error toggling active:", err);
    }
  };

  const copySqlCode = () => {
    navigator.clipboard.writeText(SESI_SQL_CODE);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  // Helper calculation for Session Status
  const getSessionTimeStatus = (sesi: SesiAbsensi) => {
    if (!sesi.is_active) return { label: "NONAKTIF", color: "bg-slate-200 text-slate-600 border-slate-300" };

    const now = new Date();
    const todayStr = getTodayString();
    
    // Check Date match
    if (sesi.tanggal !== todayStr) {
      if (sesi.tanggal < todayStr) return { label: "SELESAI", color: "bg-slate-100 text-slate-500 border-slate-200" };
      return { label: "MENDATANG", color: "bg-blue-50 text-blue-700 border-blue-200" };
    }

    const currentMinutes = now.getHours() * 60 + now.getMinutes();

    const [startH, startM] = sesi.jam_mulai.split(":").map(Number);
    const startMinutes = startH * 60 + startM;

    const [endH, endM] = sesi.jam_selesai.split(":").map(Number);
    const endMinutes = endH * 60 + endM;

    if (currentMinutes >= startMinutes && currentMinutes <= endMinutes) {
      return { label: "SEDANG BERLANGSUNG (OTOMATIS AKTIF)", color: "bg-emerald-100 text-emerald-800 border-emerald-300 animate-pulse" };
    } else if (currentMinutes < startMinutes) {
      return { label: "MENDATANG HARI INI", color: "bg-amber-50 text-amber-800 border-amber-200" };
    } else {
      return { label: "SELESAI HARI INI", color: "bg-slate-100 text-slate-500 border-slate-200" };
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header Card */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Clock className="w-6 h-6 text-[#203598]" />
            Manajemen Sesi Absensi
          </h2>
          <p className="text-slate-500 text-xs mt-1">
            Atur waktu &amp; sesi presensi. Absensi akan otomatis aktif saat jam masuk sesuai jadwal sesi.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowSql(!showSql)}
            className="px-3.5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-2 transition-colors border border-slate-200"
          >
            <Code className="w-4 h-4 text-[#203598]" />
            {showSql ? "Sembunyikan SQL" : "Kode SQL Sesi"}
          </button>

          <button
            onClick={openAddModal}
            className="px-4 py-2 bg-[#203598] hover:bg-[#1a2c7d] text-white rounded-xl text-xs font-semibold shadow-md flex items-center gap-2 transition-all active:scale-95"
          >
            <Plus className="w-4 h-4" />
            Tambah Sesi Baru
          </button>
        </div>
      </div>

      {/* SQL Helper Script Card */}
      {showSql && (
        <div className="bg-slate-900 text-slate-100 rounded-2xl p-6 shadow-xl border border-slate-800 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm">
              <Database className="w-5 h-5" />
              <span>Kode SQL Tabel &apos;sesi_absensi&apos;</span>
            </div>
            <button
              onClick={copySqlCode}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors border border-slate-700"
            >
              {copiedSql ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  Tersalin!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Salin SQL
                </>
              )}
            </button>
          </div>
          <p className="text-xs text-slate-400">
            Jalankan skrip ini di <strong>Supabase Dashboard &gt; SQL Editor &gt; Run</strong> untuk menyimpan data sesi di cloud.
          </p>
          <pre className="bg-black/50 p-4 rounded-xl text-xs font-mono text-emerald-400 overflow-x-auto whitespace-pre-wrap leading-relaxed border border-slate-800">
            {SESI_SQL_CODE}
          </pre>
        </div>
      )}

      {/* Feedback Message */}
      {message && (
        <div
          className={`p-4 rounded-xl text-sm flex items-start gap-3 shadow-sm border ${
            message.type === "success"
              ? "bg-emerald-50 text-emerald-800 border-emerald-200"
              : message.type === "error"
              ? "bg-red-50 text-red-800 border-red-200"
              : "bg-blue-50 text-blue-800 border-blue-200"
          }`}
        >
          {message.type === "success" ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
          ) : message.type === "error" ? (
            <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
          ) : (
            <Info className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
          )}
          <div className="flex-1 font-medium">{message.text}</div>
        </div>
      )}

      {/* Info Banner: Cara Kerja Otomatisasi Sesi */}
      <div className="p-4 bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200/80 rounded-2xl flex items-start gap-3.5 shadow-sm">
        <Sparkles className="w-5 h-5 text-[#203598] shrink-0 mt-0.5" />
        <div className="text-xs text-slate-700 space-y-1">
          <p className="font-bold text-slate-900 text-sm">Otomatisasi Absensi Berdasarkan Sesi</p>
          <p className="leading-relaxed">
            Sistem akan secara otomatis mendeteksi jam dan tanggal saat ini. Ketika waktu menunjukkan rentang jam dari suatu sesi yang aktif, status presensi akan secara otomatis bertanda <strong>&quot;SEDANG BERLANGSUNG&quot;</strong> di halaman Presensi.
          </p>
        </div>
      </div>

      {/* Table Sesi List */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
          <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
            Daftar Sesi Presensi ({sesiList.length})
          </span>
          <button
            onClick={fetchSesiList}
            className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
            title="Refresh Data"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin text-[#203598]" : ""}`} />
          </button>
        </div>

        {loading ? (
          <div className="p-12 text-center text-slate-400 text-sm flex items-center justify-center gap-2">
            <RefreshCw className="w-5 h-5 animate-spin text-[#203598]" />
            Memuat daftar sesi...
          </div>
        ) : sesiList.length === 0 ? (
          <div className="p-12 text-center text-slate-400 space-y-3">
            <Clock className="w-12 h-12 text-slate-300 mx-auto" />
            <p className="text-sm font-medium">Belum ada sesi absensi yang dibuat.</p>
            <button
              onClick={openAddModal}
              className="px-4 py-2 bg-[#203598] text-white rounded-xl text-xs font-semibold inline-flex items-center gap-2"
            >
              <Plus className="w-4 h-4" />
              Buat Sesi Pertama
            </button>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 text-xs font-bold uppercase tracking-wider">
                  <th className="px-6 py-3.5">Nama Sesi</th>
                  <th className="px-6 py-3.5">Tanggal</th>
                  <th className="px-6 py-3.5">Rentang Waktu</th>
                  <th className="px-6 py-3.5">Status Otomatis</th>
                  <th className="px-6 py-3.5 text-center">Aktifkan</th>
                  <th className="px-6 py-3.5 text-right w-28">Aksi</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-sm">
                {sesiList.map((sesi) => {
                  const statusInfo = getSessionTimeStatus(sesi);
                  return (
                    <tr key={sesi.id} className="hover:bg-slate-50/80 transition-colors">
                      <td className="px-6 py-4">
                        <div className="font-bold text-slate-800">{sesi.nama_sesi}</div>
                        {sesi.keterangan && (
                          <div className="text-xs text-slate-400 mt-0.5">{sesi.keterangan}</div>
                        )}
                      </td>
                      <td className="px-6 py-4 text-slate-600 font-medium whitespace-nowrap">
                        <span className="flex items-center gap-1.5 text-xs">
                          <Calendar className="w-3.5 h-3.5 text-slate-400" />
                          {new Date(sesi.tanggal).toLocaleDateString("id-ID", {
                            day: "numeric",
                            month: "short",
                            year: "numeric",
                          })}
                        </span>
                      </td>
                      <td className="px-6 py-4 font-mono font-semibold text-xs text-slate-700 whitespace-nowrap">
                        <span className="flex items-center gap-1.5 bg-slate-100 px-2.5 py-1 rounded-lg border border-slate-200 w-fit">
                          <Clock className="w-3.5 h-3.5 text-slate-500" />
                          {sesi.jam_mulai.slice(0, 5)} - {sesi.jam_selesai.slice(0, 5)} WIB
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span
                          className={`px-3 py-1 rounded-full text-[11px] font-bold border ${statusInfo.color}`}
                        >
                          {statusInfo.label}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-center whitespace-nowrap">
                        <button
                          onClick={() => handleToggleActive(sesi)}
                          className="inline-flex items-center gap-1 text-xs font-bold transition-transform active:scale-95"
                          title={sesi.is_active ? "Klik untuk nonaktifkan sesi" : "Klik untuk aktifkan sesi"}
                        >
                          {sesi.is_active ? (
                            <ToggleRight className="w-7 h-7 text-emerald-600" />
                          ) : (
                            <ToggleLeft className="w-7 h-7 text-slate-300" />
                          )}
                        </button>
                      </td>
                      <td className="px-6 py-4 text-right whitespace-nowrap">
                        <div className="flex items-center justify-end gap-1">
                          <button
                            onClick={() => openEditModal(sesi)}
                            className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                            title="Edit Sesi"
                          >
                            <Edit className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => handleDeleteSesi(sesi.id, sesi.nama_sesi)}
                            className="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                            title="Hapus Sesi"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Modal Add / Edit Sesi */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-2xl border border-slate-200 space-y-5 animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                <Clock className="w-5 h-5 text-[#203598]" />
                {editingSesi ? "Edit Sesi Absensi" : "Tambah Sesi Absensi Baru"}
              </h3>
              <button
                onClick={() => setIsModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 p-1 rounded-lg"
              >
                &times;
              </button>
            </div>

            <form onSubmit={handleSaveSesi} className="space-y-4">
              <div>
                <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                  Nama Sesi <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={formNamaSesi}
                  onChange={(e) => setFormNamaSesi(e.target.value)}
                  placeholder="Contoh: Sesi Pagi - Materi CAI"
                  required
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div>
                  <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                    Tanggal <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="date"
                    value={formTanggal}
                    onChange={(e) => setFormTanggal(e.target.value)}
                    required
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                  />
                </div>

                <div>
                  <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                    Jam Mulai <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="time"
                    value={formJamMulai}
                    onChange={(e) => setFormJamMulai(e.target.value)}
                    required
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                  />
                </div>

                <div>
                  <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                    Jam Selesai <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="time"
                    value={formJamSelesai}
                    onChange={(e) => setFormJamSelesai(e.target.value)}
                    required
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                  />
                </div>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                  Keterangan Tambahan
                </label>
                <input
                  type="text"
                  value={formKeterangan}
                  onChange={(e) => setFormKeterangan(e.target.value)}
                  placeholder="Keterangan opsional untuk sesi ini"
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                />
              </div>

              <div className="flex items-center gap-2 pt-2">
                <input
                  type="checkbox"
                  id="formIsActive"
                  checked={formIsActive}
                  onChange={(e) => setFormIsActive(e.target.checked)}
                  className="w-4 h-4 text-[#203598] rounded border-slate-300 focus:ring-[#203598]"
                />
                <label htmlFor="formIsActive" className="text-xs font-semibold text-slate-700">
                  Aktifkan Sesi Ini untuk Absensi Otomatis
                </label>
              </div>

              <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-xl text-xs font-semibold transition-colors"
                >
                  Batal
                </button>
                <button
                  type="submit"
                  disabled={saving}
                  className="px-5 py-2.5 bg-[#203598] hover:bg-[#1a2c7d] text-white rounded-xl text-xs font-semibold shadow-md transition-all flex items-center gap-2"
                >
                  {saving ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      Menyimpan...
                    </>
                  ) : (
                    "Simpan Sesi"
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
