"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import {
  Clock,
  Plus,
  Trash2,
  Edit,
  Edit2,
  Eye,
  Check,
  CheckCircle2,
  XCircle,
  Copy,
  Code,
  Database,
  Info,
  RefreshCw,
  AlertCircle,
  Calendar,
  Sparkles,
  ToggleLeft,
  ToggleRight,
  Utensils,
  BookOpen,
  Moon,
  FileSpreadsheet,
  Search,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  X,
  Filter,
} from "lucide-react";
import { supabase } from "@/lib/supabase";
import { exportDataToExcel } from "@/lib/excelExport";
import { toTitleCase, getLocalDateString } from "@/lib/utils";

export interface SesiAbsensi {
  id: number;
  nama_sesi: string;
  tanggal: string; // YYYY-MM-DD
  jam_mulai: string; // HH:mm
  jam_selesai: string; // HH:mm
  waktu_telat?: string; // HH:mm (Batas Waktu Telat)
  toleransi_menit?: number; // Toleransi menit telat (misal 15)
  is_active: boolean;
  keterangan?: string;
  kategori?: "materi" | "makan" | "sholat" | string;
  jadwal?: "materi" | "makan" | "sholat" | string;
}

// Helper untuk hitung batas jam telat berdasarkan jam mulai + menit toleransi
export function calculateWaktuTelat(jamMulai: string, toleransiMenit: number = 15): string {
  if (!jamMulai) return "08:15";
  try {
    const [hStr, mStr] = jamMulai.split(":");
    let totalMinutes = (parseInt(hStr, 10) || 0) * 60 + (parseInt(mStr, 10) || 0) + (toleransiMenit || 0);
    if (totalMinutes < 0) totalMinutes = 0;
    if (totalMinutes >= 24 * 60) totalMinutes = totalMinutes % (24 * 60);

    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}`;
  } catch (e) {
    return jamMulai;
  }
}

const SESI_SQL_CODE = `-- ==============================================================================
-- SKRIP SQL: PENAMBAHAN KOLOM WAKTU TELAT & STATUS KEHADIRAN DI SUPABASE
-- Jalankan skrip ini di Supabase Dashboard > SQL Editor > Run
-- ==============================================================================

-- 1. Tambah Kolom 'waktu_telat' & 'toleransi_menit' ke Tabel 'jadwal_absensi'
ALTER TABLE public.jadwal_absensi 
ADD COLUMN IF NOT EXISTS waktu_telat TIME;

ALTER TABLE public.jadwal_absensi 
ADD COLUMN IF NOT EXISTS toleransi_menit INTEGER DEFAULT 15;

-- 2. Tambah Kolom 'waktu_telat' & 'toleransi_menit' ke Tabel 'sesi_absensi'
ALTER TABLE public.sesi_absensi 
ADD COLUMN IF NOT EXISTS waktu_telat TIME;

ALTER TABLE public.sesi_absensi 
ADD COLUMN IF NOT EXISTS toleransi_menit INTEGER DEFAULT 15;

-- 3. Tambah Kolom 'status_kehadiran' & 'menit_terlambat' ke Tabel 'riwayat_absen'
ALTER TABLE public.riwayat_absen 
ADD COLUMN IF NOT EXISTS status_kehadiran TEXT DEFAULT 'Tepat Waktu';

ALTER TABLE public.riwayat_absen 
ADD COLUMN IF NOT EXISTS menit_terlambat INTEGER DEFAULT 0;

ALTER TABLE public.riwayat_absen 
ADD COLUMN IF NOT EXISTS waktu_telat TIME;

-- 4. Tambah Kolom 'status_kehadiran' & 'menit_terlambat' ke Tabel 'kehadiran'
ALTER TABLE public.kehadiran 
ADD COLUMN IF NOT EXISTS status_kehadiran TEXT DEFAULT 'Tepat Waktu';

ALTER TABLE public.kehadiran 
ADD COLUMN IF NOT EXISTS menit_terlambat INTEGER DEFAULT 0;

ALTER TABLE public.kehadiran 
ADD COLUMN IF NOT EXISTS waktu_telat TIME;

-- ==============================================================================
-- (OPSIONAL) DEFINISI LENGKAP JIKA TABEL BELUM DIBUAT DARI AWAL
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.jadwal_absensi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nama_sesi TEXT NOT NULL,
  tanggal DATE NOT NULL,
  jam_mulai TIME NOT NULL,
  waktu_telat TIME DEFAULT '08:15:00',
  toleransi_menit INTEGER DEFAULT 15,
  jam_selesai TIME NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  keterangan TEXT DEFAULT '',
  jadwal TEXT DEFAULT 'materi',
  kategori TEXT DEFAULT 'materi'
);

CREATE TABLE IF NOT EXISTS public.sesi_absensi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nama_sesi TEXT NOT NULL,
  tanggal DATE NOT NULL,
  jam_mulai TIME NOT NULL,
  waktu_telat TIME DEFAULT '08:15:00',
  toleransi_menit INTEGER DEFAULT 15,
  jam_selesai TIME NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  keterangan TEXT DEFAULT '',
  jadwal TEXT DEFAULT 'materi',
  kategori TEXT DEFAULT 'materi'
);

-- Kebijakan Akses Penuh (RLS)
ALTER TABLE public.jadwal_absensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sesi_absensi ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access jadwal_absensi" ON public.jadwal_absensi;
CREATE POLICY "Allow full access jadwal_absensi" ON public.jadwal_absensi FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access sesi_absensi" ON public.sesi_absensi;
CREATE POLICY "Allow full access sesi_absensi" ON public.sesi_absensi FOR ALL USING (true) WITH CHECK (true);`;

interface ManajemenSesiProps {
  kategori?: "materi" | "makan" | "sholat";
}

export default function ManajemenSesi({ kategori = "materi" }: ManajemenSesiProps) {
  const [sesiList, setSesiList] = useState<SesiAbsensi[]>([]);
  const [loading, setLoading] = useState(true);
  const [showSql, setShowSql] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error" | "info"; text: string } | null>(null);

  // Form State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingSesi, setEditingSesi] = useState<SesiAbsensi | null>(null);
  const [deletingSesi, setDeletingSesi] = useState<SesiAbsensi | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const getTodayString = () => {
    return getLocalDateString(new Date());
  };

  const [formNamaSesi, setFormNamaSesi] = useState("");
  const [formTanggal, setFormTanggal] = useState(getTodayString());
  const [formJamMulai, setFormJamMulai] = useState("08:00");
  const [formJamSelesai, setFormJamSelesai] = useState("11:30");
  const [formToleransiMenit, setFormToleransiMenit] = useState<number>(15);
  const [formWaktuTelat, setFormWaktuTelat] = useState("08:15");
  const [formIsActive, setFormIsActive] = useState(true);
  const [formKeterangan, setFormKeterangan] = useState("");
  const [formKategori, setFormKategori] = useState<"materi" | "makan" | "sholat">(kategori);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setFormKategori(kategori);
  }, [kategori]);

  // Category Info Mapping
  const categoryMeta = useMemo(() => {
    switch (kategori) {
      case "makan":
        return {
          title: "Jadwal Makan",
          subtitle: "Atur jadwal presensi makan (Sarapan, Makan Siang, Makan Malam). Absensi otomatis aktif saat jam makan.",
          icon: <Utensils className="w-6 h-6 text-[#203598]" />,
          badgeColor: "bg-amber-100 text-amber-800 border-amber-300",
          defaultName: "Makan Siang - Prasmanan",
        };
      case "sholat":
        return {
          title: "Jadwal Sholat",
          subtitle: "Atur jadwal presensi sholat berjamaah (Subuh, Dzuhur, Ashar, Maghrib, Isya). Absensi otomatis aktif saat waktu sholat.",
          icon: <Moon className="w-6 h-6 text-[#203598]" />,
          badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
          defaultName: "Sholat Subuh Berjamaah",
        };
      case "materi":
      default:
        return {
          title: "Jadwal Materi",
          subtitle: "Atur jadwal & materi penyampaian CAI 2026. Absensi otomatis aktif sesuai rentang jam materi.",
          icon: <BookOpen className="w-6 h-6 text-[#203598]" />,
          badgeColor: "bg-blue-100 text-blue-800 border-blue-300",
          defaultName: "Sesi Pagi - Materi CAI",
        };
    }
  }, [kategori]);

  const fetchSesiList = useCallback(async () => {
    setLoading(true);
    try {
      const [resJadwal, resSesi] = await Promise.all([
        supabase
          .from("jadwal_absensi")
          .select("*")
          .order("tanggal", { ascending: false })
          .order("jam_mulai", { ascending: true }),
        supabase
          .from("sesi_absensi")
          .select("*")
          .order("tanggal", { ascending: false })
          .order("jam_mulai", { ascending: true }),
      ]);

      const combined: SesiAbsensi[] = [];
      const seenKeys = new Set<string>();

      if (resJadwal.data && resJadwal.data.length > 0) {
        for (const item of resJadwal.data) {
          const key = `${item.id}-${item.nama_sesi}-${item.tanggal}-${item.jam_mulai}`;
          seenKeys.add(key);
          combined.push({
            ...item,
            nama_sesi: toTitleCase(item.nama_sesi),
            keterangan: item.keterangan ? toTitleCase(item.keterangan) : "",
          });
        }
      }

      if (resSesi.data && resSesi.data.length > 0) {
        for (const item of resSesi.data) {
          const key = `${item.id}-${item.nama_sesi}-${item.tanggal}-${item.jam_mulai}`;
          if (!seenKeys.has(key)) {
            combined.push({
              ...item,
              nama_sesi: toTitleCase(item.nama_sesi),
              keterangan: item.keterangan ? toTitleCase(item.keterangan) : "",
            });
          }
        }
      }

      if (combined.length === 0 && (resJadwal.error || resSesi.error)) {
        console.warn("Supabase fetch error / tables missing:", resJadwal.error, resSesi.error);
        const localData = localStorage.getItem("cai_sesi_absensi");
        if (localData) {
          setSesiList(JSON.parse(localData));
        } else {
          // Default Sample Sessions across categories
          const today = getTodayString();
          const defaultSample: SesiAbsensi[] = [
            {
              id: 1,
              nama_sesi: "Sesi Pagi - Materi CAI",
              tanggal: today,
              jam_mulai: "07:30",
              jam_selesai: "12:00",
              is_active: true,
              keterangan: "Absensi kehadiran materi sesi pagi",
              kategori: "materi",
              jadwal: "materi",
            },
            {
              id: 2,
              nama_sesi: "Sesi Siang - Diskusi Kelompok",
              tanggal: today,
              jam_mulai: "13:00",
              jam_selesai: "16:00",
              is_active: true,
              keterangan: "Absensi kelompok diskusi materi siang",
              kategori: "materi",
              jadwal: "materi",
            },
            {
              id: 3,
              nama_sesi: "Sarapan Pagi",
              tanggal: today,
              jam_mulai: "06:00",
              jam_selesai: "07:30",
              is_active: true,
              keterangan: "Presensi konsumsi sarapan pagi",
              kategori: "makan",
              jadwal: "makan",
            },
            {
              id: 4,
              nama_sesi: "Makan Siang Prasmanan",
              tanggal: today,
              jam_mulai: "12:00",
              jam_selesai: "13:00",
              is_active: true,
              keterangan: "Presensi konsumsi makan siang",
              kategori: "makan",
              jadwal: "makan",
            },
            {
              id: 5,
              nama_sesi: "Sholat Subuh Berjamaah",
              tanggal: today,
              jam_mulai: "04:15",
              jam_selesai: "05:30",
              is_active: true,
              keterangan: "Presensi sholat subuh berjamaah",
              kategori: "sholat",
              jadwal: "sholat",
            },
            {
              id: 6,
              nama_sesi: "Sholat Dzuhur & Ashar",
              tanggal: today,
              jam_mulai: "11:45",
              jam_selesai: "15:30",
              is_active: true,
              keterangan: "Presensi sholat dzuhur dan ashar",
              kategori: "sholat",
              jadwal: "sholat",
            },
          ];
          setSesiList(defaultSample);
          localStorage.setItem("cai_sesi_absensi", JSON.stringify(defaultSample));
        }
      } else {
        setSesiList(combined);
      }
    } catch (err) {
      console.error("Error fetching sesi:", err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchSesiList();
  }, [fetchSesiList]);

  // Filter state
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedStatus, setSelectedStatus] = useState<string>("ALL");
  const [selectedTanggal, setSelectedTanggal] = useState<string>("ALL");

  // Distinct tanggal options
  const tanggalOptions = useMemo(() => {
    const dates = new Set<string>();
    sesiList.forEach((s) => {
      if (s.tanggal) dates.add(s.tanggal);
    });
    return Array.from(dates).sort();
  }, [sesiList]);

  const handleResetFilter = () => {
    setSearchTerm("");
    setSelectedStatus("ALL");
    setSelectedTanggal("ALL");
  };

  // Filter sessions by category & filters
  const filteredSesiList = useMemo(() => {
    return sesiList.filter((s) => {
      const cat = (s.jadwal || s.kategori || "").toLowerCase();
      let matchesCategory = false;
      if (cat === "makan" || cat === "sholat" || cat === "materi") {
        matchesCategory = cat === kategori;
      } else {
        const text = (s.nama_sesi + " " + (s.keterangan || "")).toLowerCase();
        if (kategori === "makan") {
          matchesCategory = text.includes("makan") || text.includes("sarapan") || text.includes("prasmanan") || text.includes("konsumsi");
        } else if (kategori === "sholat") {
          matchesCategory =
            text.includes("sholat") ||
            text.includes("subuh") ||
            text.includes("dzuhur") ||
            text.includes("ashar") ||
            text.includes("maghrib") ||
            text.includes("isya");
        } else {
          matchesCategory = !text.includes("makan") && !text.includes("sarapan") && !text.includes("prasmanan") && !text.includes("sholat");
        }
      }

      if (!matchesCategory) return false;

      // Search term
      const sTerm = searchTerm.toLowerCase();
      const matchesSearch =
        !searchTerm ||
        s.nama_sesi.toLowerCase().includes(sTerm) ||
        (s.keterangan && s.keterangan.toLowerCase().includes(sTerm));

      // Status filter
      const matchesStatus =
        selectedStatus === "ALL" ||
        (selectedStatus === "AKTIF" && s.is_active) ||
        (selectedStatus === "NONAKTIF" && !s.is_active);

      // Tanggal filter
      const matchesTanggal =
        selectedTanggal === "ALL" || s.tanggal === selectedTanggal;

      return matchesSearch && matchesStatus && matchesTanggal;
    });
  }, [sesiList, kategori, searchTerm, selectedStatus, selectedTanggal]);

  // Pagination
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const totalPages = Math.ceil(filteredSesiList.length / pageSize) || 1;
  const paginatedSesiList = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return filteredSesiList.slice(start, start + pageSize);
  }, [filteredSesiList, currentPage, pageSize]);

  const openAddModal = () => {
    setEditingSesi(null);
    setFormKategori(kategori);
    setFormTanggal(getTodayString());
    let defaultStart = "08:00";
    let defaultEnd = "11:30";
    if (kategori === "makan") {
      setFormNamaSesi(categoryMeta.defaultName || "Makan Siang - Prasmanan");
      defaultStart = "12:00";
      defaultEnd = "13:00";
    } else if (kategori === "sholat") {
      setFormNamaSesi(categoryMeta.defaultName || "Sholat Subuh Berjamaah");
      defaultStart = "04:15";
      defaultEnd = "05:30";
    } else {
      setFormNamaSesi("Sesi Pagi - Materi CAI");
      defaultStart = "08:00";
      defaultEnd = "11:30";
    }
    setFormJamMulai(defaultStart);
    setFormJamSelesai(defaultEnd);
    setFormToleransiMenit(15);
    setFormWaktuTelat(calculateWaktuTelat(defaultStart, 15));
    setFormIsActive(true);
    setFormKeterangan("");
    setIsModalOpen(true);
  };

  const openEditModal = (sesi: SesiAbsensi) => {
    setEditingSesi(sesi);
    setFormNamaSesi(sesi.nama_sesi);
    setFormTanggal(sesi.tanggal);
    const start = sesi.jam_mulai.slice(0, 5);
    setFormJamMulai(start);
    setFormJamSelesai(sesi.jam_selesai.slice(0, 5));
    const toleransi = typeof sesi.toleransi_menit === "number" ? sesi.toleransi_menit : 15;
    setFormToleransiMenit(toleransi);
    const wt = sesi.waktu_telat ? sesi.waktu_telat.slice(0, 5) : calculateWaktuTelat(start, toleransi);
    setFormWaktuTelat(wt);
    setFormIsActive(sesi.is_active);
    setFormKeterangan(sesi.keterangan || "");
    const existingCat = (sesi.jadwal || sesi.kategori || kategori) as "materi" | "makan" | "sholat";
    setFormKategori(existingCat);
    setIsModalOpen(true);
  };

  const handleSaveSesi = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formNamaSesi.trim()) {
      setMessage({ type: "error", text: "Nama sesi wajib diisi." });
      return;
    }

    setSaving(true);
    setMessage(null);

    const targetCat = formKategori || kategori;
    const finalWaktuTelat = formWaktuTelat || calculateWaktuTelat(formJamMulai, formToleransiMenit);

    const payload = {
      nama_sesi: toTitleCase(formNamaSesi.trim()),
      tanggal: formTanggal,
      jam_mulai: formJamMulai,
      jam_selesai: formJamSelesai,
      waktu_telat: finalWaktuTelat,
      toleransi_menit: formToleransiMenit,
      is_active: formIsActive,
      keterangan: formKeterangan.trim() ? toTitleCase(formKeterangan.trim()) : "",
      kategori: targetCat,
      jadwal: targetCat,
    };

    try {
      if (editingSesi) {
        // Update both tables
        await Promise.allSettled([
          supabase.from("jadwal_absensi").update(payload).eq("id", editingSesi.id),
          supabase.from("sesi_absensi").update(payload).eq("id", editingSesi.id),
        ]);
        await fetchSesiList();
        setMessage({ type: "success", text: `Jadwal "${formNamaSesi}" berhasil diperbarui.` });
      } else {
        // Insert into both 'jadwal_absensi' and 'sesi_absensi'
        const saveJadwal = async () => {
          const { error } = await supabase.from("jadwal_absensi").insert([payload]);
          if (error) {
            const { error: err2 } = await supabase.from("jadwal_absensi").insert([
              {
                nama_sesi: payload.nama_sesi,
                tanggal: payload.tanggal,
                jam_mulai: payload.jam_mulai,
                jam_selesai: payload.jam_selesai,
                is_active: payload.is_active,
                keterangan: payload.keterangan,
                jadwal: targetCat,
              },
            ]);
            return err2;
          }
          return null;
        };

        const saveSesi = async () => {
          const { error } = await supabase.from("sesi_absensi").insert([payload]);
          if (error) {
            const { error: err2 } = await supabase.from("sesi_absensi").insert([
              {
                nama_sesi: payload.nama_sesi,
                tanggal: payload.tanggal,
                jam_mulai: payload.jam_mulai,
                jam_selesai: payload.jam_selesai,
                is_active: payload.is_active,
                keterangan: payload.keterangan,
                jadwal: targetCat,
              },
            ]);
            return err2;
          }
          return null;
        };

        const [jRes, sRes] = await Promise.all([saveJadwal(), saveSesi()]);

        if (jRes && sRes) {
          // Fallback local storage if both failed
          const newItem: SesiAbsensi = {
            id: Date.now(),
            ...payload,
          };
          const updated = [newItem, ...sesiList];
          setSesiList(updated);
          localStorage.setItem("cai_sesi_absensi", JSON.stringify(updated));
        } else {
          await fetchSesiList();
        }

        setMessage({ type: "success", text: `Jadwal "${formNamaSesi}" berhasil ditambahkan.` });
      }

      setIsModalOpen(false);
    } catch (err: any) {
      console.error("Error saving sesi:", err);
      setMessage({ type: "error", text: err.message || "Gagal menyimpan jadwal." });
    } finally {
      setSaving(false);
    }
  };

  const handlePromptDelete = (sesi: SesiAbsensi) => {
    setDeletingSesi(sesi);
  };

  const confirmDeleteSesi = async () => {
    if (!deletingSesi) return;
    const target = deletingSesi;
    setIsDeleting(true);

    try {
      // 1. Optimistic removal from UI state immediately
      const updated = sesiList.filter(
        (s) => s.id !== target.id && !(s.nama_sesi === target.nama_sesi && s.tanggal === target.tanggal)
      );
      setSesiList(updated);
      localStorage.setItem("cai_sesi_absensi", JSON.stringify(updated));

      // 2. Delete from Supabase tables (by id, and also by nama_sesi + tanggal to clean both tables)
      const deleteOps = [
        supabase.from("jadwal_absensi").delete().eq("id", target.id),
        supabase.from("sesi_absensi").delete().eq("id", target.id),
      ];

      if (target.nama_sesi) {
        deleteOps.push(
          supabase.from("jadwal_absensi").delete().match({ nama_sesi: target.nama_sesi, tanggal: target.tanggal }),
          supabase.from("sesi_absensi").delete().match({ nama_sesi: target.nama_sesi, tanggal: target.tanggal })
        );
      }

      await Promise.allSettled(deleteOps);

      // Re-fetch to ensure sync
      await fetchSesiList();
      setMessage({ type: "success", text: `Jadwal "${target.nama_sesi}" berhasil dihapus.` });
    } catch (err: any) {
      console.error("Error deleting sesi:", err);
      setMessage({ type: "error", text: "Gagal menghapus jadwal dari database." });
    } finally {
      setIsDeleting(false);
      setDeletingSesi(null);
    }
  };

  const handleToggleActive = async (sesi: SesiAbsensi) => {
    const updatedStatus = !sesi.is_active;
    try {
      await Promise.allSettled([
        supabase.from("jadwal_absensi").update({ is_active: updatedStatus }).eq("id", sesi.id),
        supabase.from("sesi_absensi").update({ is_active: updatedStatus }).eq("id", sesi.id),
      ]);
      const updated = sesiList.map((s) => (s.id === sesi.id ? { ...s, is_active: updatedStatus } : s));
      setSesiList(updated);
      localStorage.setItem("cai_sesi_absensi", JSON.stringify(updated));
      await fetchSesiList();
    } catch (err) {
      console.error("Error toggling active:", err);
    }
  };

  const copySqlCode = () => {
    navigator.clipboard.writeText(SESI_SQL_CODE);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  // Helper calculation for Session Status
  const getSessionTimeStatus = (sesi: SesiAbsensi) => {
    if (!sesi.is_active) return { label: "NONAKTIF", color: "bg-slate-200 text-slate-600 border-slate-300" };

    const now = new Date();
    const todayStr = getTodayString();
    
    // Check Date match
    if (sesi.tanggal !== todayStr) {
      if (sesi.tanggal < todayStr) return { label: "SELESAI", color: "bg-slate-100 text-slate-500 border-slate-200" };
      return { label: "MENDATANG", color: "bg-blue-50 text-blue-700 border-blue-200" };
    }

    const currentMinutes = now.getHours() * 60 + now.getMinutes();

    const [startH, startM] = sesi.jam_mulai.split(":").map(Number);
    const startMinutes = startH * 60 + startM;

    const [endH, endM] = sesi.jam_selesai.split(":").map(Number);
    const endMinutes = endH * 60 + endM;

    if (currentMinutes >= startMinutes && currentMinutes <= endMinutes) {
      return { label: "SEDANG BERLANGSUNG (OTOMATIS AKTIF)", color: "bg-emerald-100 text-emerald-800 border-emerald-300 animate-pulse" };
    } else if (currentMinutes < startMinutes) {
      return { label: "MENDATANG HARI INI", color: "bg-amber-50 text-amber-800 border-amber-200" };
    } else {
      return { label: "SELESAI HARI INI", color: "bg-slate-100 text-slate-500 border-slate-200" };
    }
  };

  // Export to Excel (.xlsx)
  const handleExportExcel = () => {
    if (filteredSesiList.length === 0) {
      alert(`Tidak ada data ${categoryMeta.title} untuk diekspor.`);
      return;
    }

    const headers = [
      "No",
      "Tanggal",
      "Nama Sesi / Kegiatan",
      "Kategori",
      "Jam Mulai (WIB)",
      "Batas Waktu Telat (WIB)",
      "Jam Selesai (WIB)",
      "Keterangan",
      "Status Aktif",
    ];

    const rows = filteredSesiList.map((s, idx) => {
      const toleransi = typeof s.toleransi_menit === "number" ? s.toleransi_menit : 15;
      const batasTelat = s.waktu_telat ? s.waktu_telat.slice(0, 5) : calculateWaktuTelat(s.jam_mulai.slice(0, 5), toleransi);
      return [
        idx + 1,
        s.tanggal,
        s.nama_sesi,
        (s.jadwal || s.kategori || "materi").toUpperCase(),
        s.jam_mulai.slice(0, 5),
        `${batasTelat} (+${toleransi}m)`,
        s.jam_selesai.slice(0, 5),
        s.keterangan || "-",
        s.is_active ? "Aktif" : "Nonaktif",
      ];
    });

    exportDataToExcel(
      `Jadwal_${categoryMeta.title.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.xlsx`,
      [
        {
          sheetName: categoryMeta.title,
          title: `JADWAL & SESI ${categoryMeta.title.toUpperCase()}`,
          subtitle: `Total ${filteredSesiList.length} Sesi Terjadwal`,
          headers,
          rows,
          customColWidths: [6, 14, 30, 16, 16, 16, 26, 14],
        },
      ]
    );
  };

  return (
    <div className="w-full max-w-7xl mx-auto space-y-5 font-sans text-slate-800">
      {/* 1. BREADCRUMB */}
      <div className="flex items-center gap-2 text-xs font-medium text-slate-500">
        <span>Jadwal & Sesi</span>
        <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
        <span className="text-slate-800 font-semibold">{categoryMeta.title}</span>
      </div>

      {/* 2. PAGE HEADER ROW */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-slate-900 tracking-tight">
            {categoryMeta.title}
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            {categoryMeta.subtitle} ({filteredSesiList.length} sesi terdaftar)
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2.5">
          <button
            onClick={handleExportExcel}
            className="px-4 py-2 bg-white hover:bg-slate-50 text-slate-700 text-xs font-semibold rounded-xl border border-slate-300 shadow-2xs flex items-center gap-2 transition-all active:scale-95"
            title={`Unduh Jadwal ${categoryMeta.title} (.xlsx)`}
          >
            <FileSpreadsheet className="w-4 h-4 text-emerald-600" />
            <span>Ekspor</span>
          </button>

          <button
            onClick={() => setShowSql(!showSql)}
            className="px-3.5 py-2 bg-white hover:bg-slate-50 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-2 transition-colors border border-slate-300 shadow-2xs"
          >
            <Code className="w-4 h-4 text-[#203598]" />
            <span>{showSql ? "Sembunyikan SQL" : "Kode SQL"}</span>
          </button>

          <button
            onClick={openAddModal}
            className="px-4 py-2 bg-[#203598] hover:bg-[#182978] text-white rounded-xl text-xs font-semibold shadow-xs flex items-center gap-2 transition-all active:scale-95"
          >
            <Plus className="w-4 h-4" />
            <span>Buat {categoryMeta.title}</span>
          </button>
        </div>
      </div>

      {/* SQL Helper Script Card */}
      {showSql && (
        <div className="bg-slate-900 text-slate-100 rounded-2xl p-6 shadow-xl border border-slate-800 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm">
              <Database className="w-5 h-5" />
              <span>Kode SQL Tabel &apos;sesi_absensi&apos;</span>
            </div>
            <button
              onClick={copySqlCode}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors border border-slate-700"
            >
              {copiedSql ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  Tersalin!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Salin SQL
                </>
              )}
            </button>
          </div>
          <p className="text-xs text-slate-400">
            Jalankan skrip ini di <strong>Supabase Dashboard &gt; SQL Editor &gt; Run</strong> untuk menyimpan data sesi di cloud.
          </p>
          <pre className="bg-black/50 p-4 rounded-xl text-xs font-mono text-emerald-400 overflow-x-auto whitespace-pre-wrap leading-relaxed border border-slate-800">
            {SESI_SQL_CODE}
          </pre>
        </div>
      )}

      {/* Feedback Message */}
      {message && (
        <div
          className={`p-4 rounded-2xl text-sm flex items-start gap-3 shadow-2xs border ${
            message.type === "success"
              ? "bg-emerald-50 text-emerald-800 border-emerald-200"
              : message.type === "error"
              ? "bg-red-50 text-red-800 border-red-200"
              : "bg-blue-50 text-blue-800 border-blue-200"
          }`}
        >
          {message.type === "success" ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
          ) : message.type === "error" ? (
            <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
          ) : (
            <Info className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
          )}
          <div className="flex-1 font-medium text-xs">{message.text}</div>
        </div>
      )}

      {/* 3. CLEAN FILTER CARD */}
      <div className="bg-white border border-slate-200/90 rounded-2xl p-5 md:p-6 shadow-2xs space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm md:text-base font-bold text-slate-900">Filter</h3>
          <button
            onClick={handleResetFilter}
            className="text-xs font-semibold text-rose-600 hover:text-rose-700 transition-colors cursor-pointer"
          >
            Atur ulang filter
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
          {/* Cari Sesi */}
          <div className="space-y-1.5">
            <label className="font-semibold text-slate-700 block">Cari Sesi / Kegiatan</label>
            <div className="relative">
              <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                placeholder="Cari nama sesi, keterangan..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-8 pr-7 py-2 bg-white border border-slate-300 rounded-xl text-xs text-slate-800 placeholder-slate-400 focus:outline-none focus:border-[#203598] focus:ring-1 focus:ring-[#203598]"
              />
              {searchTerm && (
                <button
                  onClick={() => setSearchTerm("")}
                  className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>

          {/* Filter Status */}
          <div className="space-y-1.5">
            <label className="font-semibold text-slate-700 block">Status Sesi</label>
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs text-slate-800 focus:outline-none focus:border-[#203598] focus:ring-1 focus:ring-[#203598]"
            >
              <option value="ALL">Semua Status</option>
              <option value="AKTIF">Hanya Aktif</option>
              <option value="NONAKTIF">Nonaktif</option>
            </select>
          </div>

          {/* Filter Tanggal */}
          <div className="space-y-1.5">
            <label className="font-semibold text-slate-700 block">Tanggal Jadwal</label>
            <select
              value={selectedTanggal}
              onChange={(e) => setSelectedTanggal(e.target.value)}
              className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs text-slate-800 focus:outline-none focus:border-[#203598] focus:ring-1 focus:ring-[#203598]"
            >
              <option value="ALL">Semua Tanggal</option>
              {tanggalOptions.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="pt-1 flex items-center justify-between">
          <button
            onClick={() => {}}
            className="px-4 py-2 bg-[#203598] hover:bg-[#182978] text-white font-semibold text-xs rounded-xl shadow-xs transition-all active:scale-95"
          >
            Terapkan filter
          </button>
          <div className="flex items-center gap-3">
            <span className="text-xs text-slate-500">
              Menampilkan <strong>{filteredSesiList.length}</strong> sesi
            </span>
            <button
              onClick={fetchSesiList}
              disabled={loading}
              className="p-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg text-xs transition-colors"
              title="Refresh Data"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
            </button>
          </div>
        </div>
      </div>

      {/* 4. MAIN TABLE CARD CONTAINER */}
      <div className="bg-white border border-slate-200/90 rounded-2xl shadow-2xs overflow-hidden">
        {loading ? (
          <div className="p-12 text-center text-slate-400 text-xs flex items-center justify-center gap-2">
            <RefreshCw className="w-5 h-5 animate-spin text-[#1d4ed8]" />
            Memuat jadwal {categoryMeta.title.toLowerCase()}...
          </div>
        ) : filteredSesiList.length === 0 ? (
          <div className="p-12 text-center text-slate-400 space-y-3">
            <Clock className="w-10 h-10 text-slate-300 mx-auto" />
            <p className="text-xs font-medium">Belum ada {categoryMeta.title.toLowerCase()} yang dibuat di database.</p>
            <button
              onClick={openAddModal}
              className="px-4 py-2 bg-[#1d4ed8] text-white rounded-xl text-xs font-semibold inline-flex items-center gap-1.5 shadow-2xs hover:bg-[#1e40af]"
            >
              <Plus className="w-4 h-4" />
              Buat {categoryMeta.title} Pertama
            </button>
          </div>
        ) : (
          <div className="overflow-x-auto min-h-[300px]">
            <table className="w-full text-left text-xs border-collapse">
              {/* TABLE HEADER */}
              <thead>
                <tr className="bg-white text-slate-800 font-semibold border-b border-slate-200/90">
                  <th className="py-3.5 px-3 w-28 text-center">
                    <span className="text-[11px] text-slate-400 font-normal">Aksi</span>
                  </th>

                  <th className="py-3.5 px-4 font-semibold text-slate-800 min-w-[200px]">
                    <div className="flex items-center gap-1">
                      <span>Nama Sesi / Kegiatan</span>
                      <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
                    </div>
                  </th>

                  <th className="py-3.5 px-4 font-semibold text-slate-800 min-w-[130px]">
                    <div className="flex items-center gap-1">
                      <span>Tanggal</span>
                      <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
                    </div>
                  </th>

                  <th className="py-3.5 px-4 font-semibold text-slate-800 min-w-[150px]">
                    <div className="flex items-center gap-1">
                      <span>Waktu Mulai - Selesai</span>
                      <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
                    </div>
                  </th>

                  <th className="py-3.5 px-4 font-semibold text-slate-800 min-w-[140px]">
                    <div className="flex items-center gap-1">
                      <span>Batas Telat</span>
                      <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
                    </div>
                  </th>

                  <th className="py-3.5 px-4 font-semibold text-slate-800 text-center min-w-[110px]">
                    <span>Kategori</span>
                  </th>

                  <th className="py-3.5 px-4 font-semibold text-slate-800 text-center min-w-[160px]">
                    <span>Status Waktu</span>
                  </th>

                  <th className="py-3.5 px-4 font-semibold text-slate-800 text-center min-w-[100px]">
                    <span>Status Aktif</span>
                  </th>
                </tr>
              </thead>

              {/* DATA ROWS */}
              <tbody className="divide-y divide-slate-100 text-slate-700 font-normal">
                {paginatedSesiList.map((sesi) => {
                  const statusInfo = getSessionTimeStatus(sesi);
                  const catType = (sesi.jadwal || sesi.kategori || "materi").toLowerCase();

                  return (
                    <tr key={sesi.id} className="hover:bg-slate-50/70 transition-colors">
                      {/* Aksi Icons */}
                      <td className="py-3.5 px-3 text-center whitespace-nowrap">
                        <div className="flex items-center justify-center gap-1.5">
                          {/* Edit */}
                          <button
                            type="button"
                            onClick={() => openEditModal(sesi)}
                            className="p-1.5 bg-[#1d4ed8] hover:bg-blue-700 text-white rounded-lg transition-colors shadow-2xs"
                            title="Edit Sesi"
                          >
                            <Edit2 className="w-3.5 h-3.5" />
                          </button>

                          {/* Delete */}
                          <button
                            type="button"
                            onClick={() => handlePromptDelete(sesi)}
                            className="p-1.5 text-slate-400 hover:text-rose-600 bg-white hover:bg-rose-50 border border-slate-200 rounded-lg shadow-2xs transition-colors cursor-pointer"
                            title="Hapus Sesi"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>

                      {/* Nama Sesi */}
                      <td className="py-3.5 px-4 font-normal">
                        <div className="flex items-center gap-3">
                          <div className="w-9 h-9 rounded-lg overflow-hidden shrink-0 flex items-center justify-center font-bold text-xs bg-blue-100 text-[#1d4ed8] border border-blue-200">
                            <Clock className="w-4 h-4" />
                          </div>
                          <div>
                            <div className="font-semibold text-slate-900 text-xs md:text-sm">
                              {sesi.nama_sesi}
                            </div>
                            <div className="text-[11px] text-slate-400 font-mono tracking-tight">
                              {sesi.keterangan || "Jadwal Resmi CAI 2026"}
                            </div>
                          </div>
                        </div>
                      </td>

                      {/* Tanggal */}
                      <td className="py-3.5 px-4 font-medium text-slate-700 whitespace-nowrap">
                        {new Date(sesi.tanggal).toLocaleDateString("id-ID", {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                        })}
                      </td>

                      {/* Waktu Mulai - Selesai */}
                      <td className="py-3.5 px-4 font-mono text-xs text-slate-700 whitespace-nowrap">
                        <div className="px-2.5 py-1 bg-white border border-slate-200 rounded-xl inline-block text-xs font-mono text-slate-700 shadow-2xs">
                          {sesi.jam_mulai.slice(0, 5)} - {sesi.jam_selesai.slice(0, 5)} WIB
                        </div>
                      </td>

                      {/* Batas Waktu Telat */}
                      <td className="py-3.5 px-4 whitespace-nowrap">
                        {(() => {
                          const toleransi = typeof sesi.toleransi_menit === "number" ? sesi.toleransi_menit : 15;
                          const batasTelat = sesi.waktu_telat ? sesi.waktu_telat.slice(0, 5) : calculateWaktuTelat(sesi.jam_mulai.slice(0, 5), toleransi);
                          return (
                            <div className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-amber-50/80 border border-amber-200 rounded-xl text-xs font-mono font-medium text-amber-800 shadow-2xs">
                              <Clock className="w-3 h-3 text-amber-600" />
                              <span>{batasTelat} WIB</span>
                              <span className="text-[10px] text-amber-600 font-sans font-bold bg-amber-100/70 px-1 py-0.2 rounded">
                                +{toleransi}m
                              </span>
                            </div>
                          );
                        })()}
                      </td>

                      {/* Kategori */}
                      <td className="py-3.5 px-4 text-center">
                        <span className="inline-block px-2.5 py-0.5 bg-blue-50 text-blue-600 border border-blue-200/90 rounded-md font-semibold text-[11px] capitalize">
                          {catType}
                        </span>
                      </td>

                      {/* Status Waktu Otomatis */}
                      <td className="py-3.5 px-4 text-center whitespace-nowrap">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-semibold border ${statusInfo.color}`}>
                          {statusInfo.label}
                        </span>
                      </td>

                      {/* Status Aktif Switch */}
                      <td className="py-3.5 px-4 text-center whitespace-nowrap">
                        <button
                          type="button"
                          onClick={() => handleToggleActive(sesi)}
                          className="inline-flex items-center gap-1 text-xs font-bold transition-transform active:scale-95 cursor-pointer"
                          title={sesi.is_active ? "Klik untuk nonaktifkan sesi" : "Klik untuk aktifkan sesi"}
                        >
                          {sesi.is_active ? (
                            <ToggleRight className="w-6 h-6 text-emerald-600" />
                          ) : (
                            <ToggleLeft className="w-6 h-6 text-slate-300" />
                          )}
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {/* 5. TABLE FOOTER */}
        <div className="bg-white border-t border-slate-200/80 px-4 py-3.5 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-600">
          <div>
            Menampilkan{" "}
            <span className="font-semibold text-slate-800">
              {filteredSesiList.length > 0 ? (currentPage - 1) * pageSize + 1 : 0}
            </span>{" "}
            sampai{" "}
            <span className="font-semibold text-slate-800">
              {Math.min(currentPage * pageSize, filteredSesiList.length)}
            </span>{" "}
            dari{" "}
            <span className="font-semibold text-slate-800">{filteredSesiList.length}</span>{" "}
            hasil
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-slate-500">per halaman</span>
              <select
                value={pageSize}
                onChange={(e) => {
                  setPageSize(Number(e.target.value));
                  setCurrentPage(1);
                }}
                className="px-2.5 py-1 bg-white border border-slate-200 rounded-lg text-xs font-semibold text-slate-700 focus:outline-none focus:border-[#1d4ed8] cursor-pointer shadow-2xs"
              >
                <option value={10}>10</option>
                <option value={25}>25</option>
                <option value={50}>50</option>
                <option value={100}>100</option>
              </select>
            </div>

            <div className="flex items-center gap-1">
              <button
                onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                disabled={currentPage === 1}
                className="p-1 rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50 disabled:opacity-30 disabled:pointer-events-none cursor-pointer"
                title="Halaman Sebelumnya"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>

              <div className="px-2 font-bold text-xs text-slate-800">
                {currentPage} / {totalPages}
              </div>

              <button
                onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
                className="p-1 rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50 disabled:opacity-30 disabled:pointer-events-none cursor-pointer"
                title="Halaman Berikutnya"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Modal Add / Edit Sesi */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-2xl border border-slate-200 space-y-5 animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                <Clock className="w-5 h-5 text-[#203598]" />
                {editingSesi ? "Edit Sesi Absensi" : "Tambah Sesi Absensi Baru"}
              </h3>
              <button
                onClick={() => setIsModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 p-1 rounded-lg"
              >
                &times;
              </button>
            </div>

            <form onSubmit={handleSaveSesi} className="space-y-4">
              <div>
                <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                  Jenis Jadwal / Kategori <span className="text-red-500">*</span>
                </label>
                <select
                  value={formKategori}
                  onChange={(e) => setFormKategori(e.target.value as any)}
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                >
                  <option value="materi">Jadwal Materi (Penyampaian CAI / Kelas)</option>
                  <option value="makan">Jadwal Makan (Sarapan / Makan Siang / Malam)</option>
                  <option value="sholat">Jadwal Sholat (Subuh / Dzuhur / Ashar / Maghrib / Isya)</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                  Nama Sesi <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={formNamaSesi}
                  onChange={(e) => setFormNamaSesi(e.target.value)}
                  placeholder="Contoh: Sesi Pagi - Materi CAI / Makan Siang"
                  required
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                    Tanggal Sesi <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="date"
                    value={formTanggal}
                    onChange={(e) => setFormTanggal(e.target.value)}
                    required
                    className="w-full px-3 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                  />
                </div>

                <div>
                  <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                    Jam Selesai <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="time"
                    value={formJamSelesai}
                    onChange={(e) => setFormJamSelesai(e.target.value)}
                    required
                    className="w-full px-3 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                  />
                </div>
              </div>

              {/* Waktu Mulai & Batas Waktu Telat Box */}
              <div className="p-3.5 bg-amber-50/50 border border-amber-200/80 rounded-2xl space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-amber-900 flex items-center gap-1.5">
                    <Clock className="w-4 h-4 text-amber-600" />
                    Pengaturan Waktu & Toleransi Telat
                  </span>
                  <span className="text-[11px] font-semibold text-amber-700">
                    Otomatis Tercatat Terlambat
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                      Jam Mulai Sesi <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="time"
                      value={formJamMulai}
                      onChange={(e) => {
                        const newStart = e.target.value;
                        setFormJamMulai(newStart);
                        setFormWaktuTelat(calculateWaktuTelat(newStart, formToleransiMenit));
                      }}
                      required
                      className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                    />
                  </div>

                  <div>
                    <label className="text-xs font-bold text-amber-900 uppercase tracking-wider block mb-1">
                      Batas Jam Telat <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="time"
                      value={formWaktuTelat}
                      onChange={(e) => setFormWaktuTelat(e.target.value)}
                      required
                      className="w-full px-3 py-2 bg-white border border-amber-300 rounded-xl text-xs font-bold text-amber-900 focus:outline-none focus:ring-2 focus:ring-amber-500/30 focus:border-amber-600 transition-all shadow-2xs"
                    />
                  </div>
                </div>

                {/* Quick Tolerance Selector */}
                <div>
                  <label className="text-[11px] font-semibold text-slate-600 block mb-1.5">
                    Pilih Cepat Toleransi Menit:
                  </label>
                  <div className="flex flex-wrap gap-1.5">
                    {[
                      { label: "Tepat Waktu (0m)", mins: 0 },
                      { label: "+5 Menit", mins: 5 },
                      { label: "+10 Menit", mins: 10 },
                      { label: "+15 Menit", mins: 15 },
                      { label: "+30 Menit", mins: 30 },
                    ].map((tol) => {
                      const isSelected = formToleransiMenit === tol.mins;
                      return (
                        <button
                          key={tol.mins}
                          type="button"
                          onClick={() => {
                            setFormToleransiMenit(tol.mins);
                            setFormWaktuTelat(calculateWaktuTelat(formJamMulai, tol.mins));
                          }}
                          className={`px-2.5 py-1 text-xs font-semibold rounded-lg border transition-all ${
                            isSelected
                              ? "bg-amber-500 text-white border-amber-600 shadow-2xs"
                              : "bg-white text-slate-700 border-slate-200 hover:bg-amber-100/50 hover:text-amber-900"
                          }`}
                        >
                          {tol.label}
                        </button>
                      );
                    })}
                  </div>
                  <p className="text-[10px] text-amber-800/80 mt-1.5 leading-tight">
                    Peserta yang tap kartu setelah pukul <strong>{formWaktuTelat || "08:15"} WIB</strong> akan otomatis diberi label <strong>Terlambat</strong>.
                  </p>
                </div>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1">
                  Keterangan Tambahan
                </label>
                <input
                  type="text"
                  value={formKeterangan}
                  onChange={(e) => setFormKeterangan(e.target.value)}
                  placeholder="Keterangan opsional untuk sesi ini"
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#203598]/20 focus:border-[#203598] transition-all"
                />
              </div>

              <div className="flex items-center gap-2 pt-2">
                <input
                  type="checkbox"
                  id="formIsActive"
                  checked={formIsActive}
                  onChange={(e) => setFormIsActive(e.target.checked)}
                  className="w-4 h-4 text-[#203598] rounded border-slate-300 focus:ring-[#203598]"
                />
                <label htmlFor="formIsActive" className="text-xs font-semibold text-slate-700">
                  Aktifkan Sesi Ini untuk Absensi Otomatis
                </label>
              </div>

              <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-xl text-xs font-semibold transition-colors"
                >
                  Batal
                </button>
                <button
                  type="submit"
                  disabled={saving}
                  className="px-5 py-2.5 bg-[#203598] hover:bg-[#1a2c7d] text-white rounded-xl text-xs font-semibold shadow-md transition-all flex items-center gap-2"
                >
                  {saving ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      Menyimpan...
                    </>
                  ) : (
                    "Simpan Sesi"
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deletingSesi && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in duration-150">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-md w-full overflow-hidden p-6 space-y-4">
            <div className="flex items-start gap-3.5">
              <div className="w-11 h-11 rounded-2xl bg-rose-100 text-rose-600 flex items-center justify-center shrink-0">
                <Trash2 className="w-5 h-5" />
              </div>
              <div className="space-y-1 flex-1">
                <h3 className="text-base font-extrabold text-slate-900">
                  Hapus Jadwal Sesi?
                </h3>
                <p className="text-xs text-slate-500 leading-relaxed">
                  Apakah Anda yakin ingin menghapus jadwal <strong className="text-slate-800">&quot;{deletingSesi.nama_sesi}&quot;</strong> ({deletingSesi.tanggal}, {deletingSesi.jam_mulai.slice(0, 5)} - {deletingSesi.jam_selesai.slice(0, 5)} WIB)?
                </p>
                <p className="text-[11px] text-rose-600 font-medium pt-1">
                  Tindakan ini akan menghapus data dari database.
                </p>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2.5 pt-3 border-t border-slate-100">
              <button
                type="button"
                onClick={() => setDeletingSesi(null)}
                disabled={isDeleting}
                className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-xl text-xs font-semibold transition-colors cursor-pointer"
              >
                Batal
              </button>
              <button
                type="button"
                onClick={confirmDeleteSesi}
                disabled={isDeleting}
                className="px-4.5 py-2 bg-rose-600 hover:bg-rose-700 disabled:opacity-50 text-white rounded-xl text-xs font-bold shadow-md shadow-rose-600/20 transition-all inline-flex items-center gap-1.5 cursor-pointer"
              >
                {isDeleting ? (
                  <>
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                    <span>Menghapus...</span>
                  </>
                ) : (
                  <>
                    <Trash2 className="w-3.5 h-3.5" />
                    <span>Ya, Hapus Jadwal</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
